import type { TeamId } from "./types";

/** Full NFL career span. Signature team is jersey color only — not a contract window. */
export type CareerFix = {
  years: string;
  team?: TeamId;
  /** Most snaps first. Defaults to the signature team. */
  teams?: TeamId[];
  note?: string;
};

export const CAREER: Record<string, CareerFix> = {
  "Patrick Mahomes": { years: "2017–present", team: "KC", note: "Three Super Bowls, two MVPs, and the no-look that broke coverages." },
  "Tom Brady": { years: "2000–2022", team: "NE", teams: ["NE", "TB"], note: "Seven rings. Twenty-three seasons. The career that is the position." },
  "Eli Manning": { years: "2004–2019", team: "NYG", note: "Two Super Bowl MVPs. The Giant who kept answering Brady in February." },
  "Robert Griffin III": { years: "2012–2020", team: "WAS", note: "Rookie-year electricity. Zone-read lightning until the knee changed the story." },
  "Carson Palmer": { years: "2003–2017", team: "CIN", teams: ["CIN", "ARI"], note: "Bengals cannon, then a Cardinals rebirth that nearly went all the way." },
  "Aaron Rodgers": { years: "2005–present", team: "GB", teams: ["GB", "NYJ"], note: "Four MVPs, a ring, and the coldest deep ball of the century." },
  "Josh Allen": { years: "2018–present", team: "BUF", note: "Cannon arm, truck-stick legs, perpetual AFC threat." },
  "Lamar Jackson": { years: "2018–present", team: "BAL", note: "Two MVPs. Dual-threat who redrew what the position can be." },
  "Drew Brees": { years: "2001–2020", team: "NO", note: "The record book: completions, yards, and a Super Bowl in New Orleans." },
  "Joe Burrow": { years: "2020–present", team: "CIN", note: "Coolest customer in stripes. Super Bowl trip in year two." },
  "Russell Wilson": { years: "2012–present", team: "SEA", teams: ["SEA", "DEN"], note: "Scramble-drill king, a Super Bowl, and a Legion of Boom peak." },
  "Ben Roethlisberger": { years: "2004–2021", team: "PIT", note: "Two rings. Extender of plays until the very last snap." },
  "Matthew Stafford": { years: "2009–present", team: "DET", teams: ["DET", "LAR"], note: "Detroit warrior who finally cashed a ring in Los Angeles." },
  "Justin Herbert": { years: "2020–present", team: "LAC", note: "Prototype arm talent still hunting a deep January." },
  "Jalen Hurts": { years: "2020–present", team: "PHI", note: "Tush-push emperor and a Super Bowl starter." },
  "Matt Ryan": { years: "2008–2022", team: "ATL", note: "2016 MVP. A Falcons career that always found the numbers." },
  "Philip Rivers": { years: "2004–2020", team: "LAC", teams: ["LAC", "IND"], note: "Sideline sermonizer. Seventeen seasons of 4,000-yard Sundays." },
  "Andrew Luck": { years: "2012–2018", team: "IND", note: "Generational talent who walked away too soon." },
  "Dak Prescott": { years: "2016–present", team: "DAL", note: "Star on the helmet, January still the question." },
  "Jared Goff": { years: "2016–present", team: "DET", teams: ["LAR", "DET"], note: "First overall, a Rams Super Bowl, then a Detroit rebirth." },
  "Jayden Daniels": { years: "2024–present", team: "WAS", note: "Rookie dynamite that dragged Washington to January." },
  "C.J. Stroud": { years: "2023–present", team: "HOU", note: "Rookie-year opera in a rebuilding huddle." },
  "Brock Purdy": { years: "2022–present", team: "SF", note: "Mr. Irrelevant who kept a dynasty humming." },
  "Deshaun Watson": { years: "2017–present", team: "HOU", teams: ["HOU", "CLE"], note: "Houston peak: scramble, throw, and take over games." },
  "Cam Newton": { years: "2011–2021", team: "CAR", teams: ["CAR", "NE"], note: "2015 MVP. Superman in Carolina, still a problem in the red zone." },
  "Jordan Love": { years: "2020–present", team: "GB", note: "The man who inherited 12 and didn't blink." },
  "Kirk Cousins": { years: "2012–present", team: "MIN", teams: ["WAS", "MIN"], note: "Fully guaranteed and fully competent across three franchises." },
  "Kyler Murray": { years: "2019–present", team: "ARI", note: "Compact dynamite when the legs are healthy." },
  "Tua Tagovailoa": { years: "2020–present", team: "MIA", note: "Rhythm passer in a speed-skill circus." },
  "Trevor Lawrence": { years: "2021–present", team: "JAX", note: "Can't-miss prospect, still becoming the guy." },
  "Derek Carr": { years: "2014–present", team: "LV", note: "Silver-and-black starter with a cannon and a conscience." },
  "Carson Wentz": { years: "2016–present", team: "PHI", note: "MVP-track 2017 in Philly before the knee changed everything." },
  "Ryan Tannehill": { years: "2012–2023", team: "MIA", note: "Dolphins years, then a Titans bloom next to Henry." },
  "Geno Smith": { years: "2013–present", team: "SEA", note: "Comeback QB of the Year after a long wilderness." },
  "Baker Mayfield": { years: "2018–present", team: "CLE", note: "First overall in Cleveland, second act that kept him starting." },
  "Bo Nix": { years: "2024–present", team: "DEN" },
  "Caleb Williams": { years: "2024–present", team: "CHI" },
  "Drake Maye": { years: "2024–present", team: "NE" },
  "Justin Fields": { years: "2021–present", team: "CHI", note: "Designed-run dynamite with a 1,000-yard rushing year." },
  "Sam Darnold": { years: "2018–present", team: "NYJ", note: "Jets first overall, then a Minnesota resurrection." },
  "Jimmy Garoppolo": { years: "2014–present", team: "SF", note: "Patriot backup who became a 49ers Super Bowl starter." },
  "Nick Foles": { years: "2012–2022", team: "PHI", note: "Philly Special. Super Bowl MVP. A career of arriving on time." },
  "Alex Smith": { years: "2005–2020", team: "SF", note: "First overall, a Chiefs peak, then the comeback that mattered." },
  "Joe Flacco": { years: "2008–present", team: "BAL", note: "Super Bowl MVP in Baltimore. Elite Dragon, then the long encore." },
  "Jameis Winston": { years: "2015–present", team: "TB", note: "First overall gunslinger. The tape was never boring." },
  "Marcus Mariota": { years: "2015–present", team: "TEN", note: "Zone-read lightning as a Titan, then a career of bridges." },
  "Andy Dalton": { years: "2011–present", team: "CIN", note: "Red Rifle. Yearly 3,500 without the January luck." },
  "Case Keenum": { years: "2012–present", team: "MIN", note: "Minneapolis Miracle starter. Journeyman with one immortal throw." },
  "Teddy Bridgewater": { years: "2014–present", team: "MIN", note: "The comeback. Calm that outlasted the knee." },
  "Gardner Minshew": { years: "2019–present", team: "JAX", note: "Mustache, no-look, and a locker room wherever he landed." },
  "Jacoby Brissett": { years: "2016–present", team: "IND", note: "Bridge starter who never mailed it in." },
  "Ryan Fitzpatrick": { years: "2005–2021", team: "BUF", note: "Fitzmagic. Nine helmets, same chaos, a 30-for-30 career." },
  "Tyrod Taylor": { years: "2011–present", team: "BUF", note: "Dual-threat who kept Buffalo afloat, then kept starting somewhere." },
  "Daniel Jones": { years: "2019–present", team: "NYG", note: "Danny Dimes. A playoff run out of nowhere." },
  "Mac Jones": { years: "2021–present", team: "NE" },
  "Anthony Richardson": { years: "2023–present", team: "IND" },
  "Cam Ward": { years: "2025–present", team: "TEN" },
  "Jaxson Dart": { years: "2025–present", team: "NYG" },
  "Christian McCaffrey": { years: "2017–present", team: "SF", note: "Swiss-army back. Rushing, receiving, and a Super Bowl." },
  "Chris Johnson": { years: "2008–2017", team: "TEN", note: "2,006 rushing yards. The 4.24 that defenses never caught." },
  "Arian Foster": { years: "2009–2016", team: "HOU", note: "Undrafted zone-scheme king. 1,600 and 16 as a first-year starter." },
  "Jamaal Charles": { years: "2008–2018", team: "KC", note: "5.4 a carry and receiving chops. The Chiefs' home-run threat." },
  "Marshawn Lynch": { years: "2007–2019", team: "SEA", note: "Beast Mode. Legion of Boom closer and a Super Bowl run." },
  "Derrick Henry": { years: "2016–present", team: "TEN", note: "King Henry. Trucks, stiff-arms, 2,000-yard thunder." },
  "Saquon Barkley": { years: "2018–present", team: "NYG", note: "Generational talent. Giants years, then a Philly explosion." },
  "Alvin Kamara": { years: "2017–present", team: "NO" },
  "Nick Chubb": { years: "2018–present", team: "CLE" },
  "Le'Veon Bell": { years: "2013–2021", team: "PIT", note: "The pause. Patient, violent, complete in Pittsburgh." },
  "Jonathan Taylor": { years: "2020–present", team: "IND" },
  "Todd Gurley": { years: "2015–2020", team: "LAR", note: "Offensive Player of the Year until the knee said no." },
  "Jahmyr Gibbs": { years: "2023–present", team: "DET" },
  "Bijan Robinson": { years: "2023–present", team: "ATL" },
  "LeSean McCoy": { years: "2009–2021", team: "PHI", note: "Shady. Make-you-miss from Philadelphia to Buffalo." },
  "Ezekiel Elliott": { years: "2016–present", team: "DAL", note: "Bell-cow with a rushing crown as a rookie." },
  "Dalvin Cook": { years: "2017–2024", team: "MIN" },
  "Josh Jacobs": { years: "2019–present", team: "LV" },
  "Breece Hall": { years: "2022–present", team: "NYJ" },
  "Aaron Jones": { years: "2017–present", team: "GB" },
  "De'Von Achane": { years: "2023–present", team: "MIA" },
  "Austin Ekeler": { years: "2017–present", team: "LAC" },
  "Joe Mixon": { years: "2017–present", team: "CIN" },
  "Kyren Williams": { years: "2022–present", team: "LAR" },
  "James Conner": { years: "2017–present", team: "PIT", note: "Goal-line hammer who outlasted the doubters in two cities." },
  "Kareem Hunt": { years: "2017–present", team: "KC", note: "Rookie rushing champ, then a long Browns encore." },
  "Mark Ingram": { years: "2011–2022", team: "NO", note: "Heisman back who became a Saint, a Raven, and a closer." },
  "Devonta Freeman": { years: "2014–2021", team: "ATL", note: "Zone-scheme scorer on a Super Bowl Falcons roster." },
  "Melvin Gordon": { years: "2015–2023", team: "LAC" },
  "Jordan Howard": { years: "2016–2022", team: "CHI" },
  "Chris Carson": { years: "2017–2021", team: "SEA" },
  "Marlon Mack": { years: "2017–present", team: "IND" },
  "Leonard Fournette": { years: "2017–2022", team: "JAX", note: "First overall Jaguar, then a Super Bowl closer in Tampa." },
  "David Johnson": { years: "2015–2022", team: "ARI", note: "All-purpose monster in Arizona before the injury fog." },
  "David Montgomery": { years: "2019–present", team: "CHI" },
  "Kenneth Walker III": { years: "2022–present", team: "SEA" },
  "James Cook": { years: "2022–present", team: "BUF" },
  "Isiah Pacheco": { years: "2022–present", team: "KC" },
  "D'Andre Swift": { years: "2020–present", team: "DET" },
  "Tony Pollard": { years: "2019–present", team: "DAL" },
  "Najee Harris": { years: "2021–present", team: "PIT" },
  "Travis Etienne": { years: "2021–present", team: "JAX" },
  "J.K. Dobbins": { years: "2020–present", team: "BAL" },
  "Devin Singletary": { years: "2019–present", team: "BUF" },
  "Miles Sanders": { years: "2019–present", team: "PHI" },
  "Javonte Williams": { years: "2021–present", team: "DEN" },
  "Rhamondre Stevenson": { years: "2021–present", team: "NE" },
  "Kenyan Drake": { years: "2016–2023", team: "MIA", note: "Monday-night walk-off, a 1,000-yard year, many backfields." },
  "A.J. Dillon": { years: "2020–present", team: "GB" },
  "Brian Robinson Jr.": { years: "2022–present", team: "WAS" },
  "Chuba Hubbard": { years: "2021–present", team: "CAR" },
  "Jaylen Warren": { years: "2022–present", team: "PIT" },
  "James White": { years: "2014–2021", team: "NE", note: "Passing-down assassin. Super Bowl walk-off in overtime." },
  "Rachaad White": { years: "2022–present", team: "TB" },
  "Rico Dowdle": { years: "2020–present", team: "DAL" },
  "Raheem Mostert": { years: "2015–present", team: "SF", note: "Outside-zone home runs. Super Bowl thunder, then Miami speed." },
  "Sony Michel": { years: "2018–2022", team: "NE" },
  "Rashaad Penny": { years: "2018–2023", team: "SEA" },
  "Jamaal Williams": { years: "2017–present", team: "GB", note: "Green Bay glue, then a Lions 1,000-yard smile." },
  "Clyde Edwards-Helaire": { years: "2020–present", team: "KC" },
  "Antonio Gibson": { years: "2020–present", team: "WAS" },
  "James Robinson": { years: "2020–2022", team: "JAX" },
  "Damien Harris": { years: "2019–2023", team: "NE" },
  "Nyheim Hines": { years: "2018–present", team: "IND" },
  "Latavius Murray": { years: "2014–2023", team: "LV", note: "Veteran closer who scored in bunches across the league." },
  "Frank Gore": { years: "2005–2020", team: "SF", note: "The mileage. Third on the all-time rushing list when he walked away." },
  "Adrian Peterson": { years: "2007–2021", team: "MIN", note: "All Day. MVP, 2,000 yards, a career that refused the script." },
  "LeGarrette Blount": { years: "2010–2018", team: "NE", note: "Goal-line tank on two Super Bowl rosters." },
  "Giovani Bernard": { years: "2013–2022", team: "CIN" },
  "Carlos Hyde": { years: "2014–2021", team: "SF" },
  "Justin Jefferson": { years: "2020–present", team: "MIN" },
  "Steve Smith": { years: "2001–2016", team: "CAR", note: "Undrafted fire. 1,563 yards and a chip on both shoulders." },
  "Andre Johnson": { years: "2003–2016", team: "HOU", note: "Contested-catch king on offenses that rarely had a quarterback." },
  "Brandon Marshall": { years: "2006–2018", team: "DEN", note: "Volume king. A 1,500-yard year in Chicago and another in New York." },
  "Josh Gordon": { years: "2012–2023", team: "CLE", note: "1,646 yards in a Browns year that still looks impossible." },
  "Anquan Boldin": { years: "2003–2016", team: "ARI", note: "Rookie explosion, then a career of contested catches and rings." },
  "Ja'Marr Chase": { years: "2021–present", team: "CIN" },
  "Davante Adams": { years: "2014–present", team: "GB", note: "The release. A WR1 in Green Bay, Las Vegas, and New York." },
  "Julio Jones": { years: "2011–2023", team: "ATL", note: "Uncoverable in his prime. The body eventually billed him." },
  "Tyreek Hill": { years: "2016–present", team: "KC", note: "Cheetah. Super Bowl speed in Kansas City, then Miami math." },
  "Antonio Brown": { years: "2010–2021", team: "PIT", note: "Route-running savant. Seven straight 1,000-yard years in Pittsburgh." },
  "DeAndre Hopkins": { years: "2013–present", team: "HOU", note: "Nuk. Hands that ignore coverage, wherever the helmet went." },
  "Mike Evans": { years: "2014–present", team: "TB", note: "1,000 yards every. single. season." },
  "Cooper Kupp": { years: "2017–present", team: "LAR" },
  "A.J. Brown": { years: "2019–present", team: "TEN", note: "Body control and contested-catch violence. Titans, then Philly." },
  "CeeDee Lamb": { years: "2020–present", team: "DAL" },
  "Stefon Diggs": { years: "2015–present", team: "MIN", note: "Minneapolis Miracle origin, then a Buffalo peak." },
  "Michael Thomas": { years: "2016–present", team: "NO" },
  "Keenan Allen": { years: "2013–present", team: "LAC", note: "Option-route professor. Always open." },
  "Amon-Ra St. Brown": { years: "2021–present", team: "DET" },
  "A.J. Green": { years: "2011–2022", team: "CIN", note: "Prototype X. Quiet, huge, seven Pro Bowls." },
  "Odell Beckham Jr.": { years: "2014–2023", team: "NYG", note: "The Catch. Then the circus. Production in three cities." },
  "DK Metcalf": { years: "2019–present", team: "SEA" },
  "Dez Bryant": { years: "2010–2017", team: "DAL", note: "Was it a catch? The production in Dallas was." },
  "Demaryius Thomas": { years: "2010–2019", team: "DEN", note: "YAC king of the Manning Broncos. A Super Bowl included." },
  "Puka Nacua": { years: "2023–present", team: "LAR" },
  "Nico Collins": { years: "2021–present", team: "HOU" },
  "Malik Nabers": { years: "2024–present", team: "NYG" },
  "Deebo Samuel": { years: "2019–present", team: "SF" },
  "Jaylen Waddle": { years: "2021–present", team: "MIA" },
  "T.Y. Hilton": { years: "2012–2022", team: "IND", note: "The Ghost. Deep threat on a weekly basis in Indianapolis." },
  "Amari Cooper": { years: "2015–present", team: "DAL", note: "Route polish. A WR1 in Oakland, Dallas, Cleveland, and Buffalo." },
  "Chris Godwin": { years: "2017–present", team: "TB" },
  "Tyler Lockett": { years: "2015–present", team: "SEA", note: "Sure hands, better vibes, yearly 1,000 in Seattle." },
  "DJ Moore": { years: "2018–present", team: "CAR" },
  "Garrett Wilson": { years: "2022–present", team: "NYJ" },
  "Adam Thielen": { years: "2013–present", team: "MIN", note: "Undrafted Minnesotan who became a star." },
  "Tee Higgins": { years: "2020–present", team: "CIN" },
  "Brandon Aiyuk": { years: "2020–present", team: "SF" },
  "Chris Olave": { years: "2022–present", team: "NO" },
  "Drake London": { years: "2022–present", team: "ATL" },
  "Brian Thomas Jr.": { years: "2024–present", team: "JAX" },
  "Marvin Harrison Jr.": { years: "2024–present", team: "ARI" },
  "Zay Flowers": { years: "2023–present", team: "BAL" },
  "Rashee Rice": { years: "2023–present", team: "KC" },
  "George Pickens": { years: "2022–present", team: "PIT" },
  "DeVonta Smith": { years: "2021–present", team: "PHI" },
  "Courtland Sutton": { years: "2018–present", team: "DEN" },
  "Terry McLaurin": { years: "2019–present", team: "WAS" },
  "Diontae Johnson": { years: "2019–present", team: "PIT" },
  "JuJu Smith-Schuster": { years: "2017–present", team: "PIT" },
  "Brandin Cooks": { years: "2014–present", team: "NO", note: "Deep threat who produced in five cities." },
  "Robert Woods": { years: "2013–present", team: "BUF" },
  "Jarvis Landry": { years: "2014–2022", team: "MIA", note: "Sun in my eyes. Slot volume king in Miami, then Cleveland." },
  "Julian Edelman": { years: "2009–2020", team: "NE", note: "Slot tough. Super Bowl MVP. The career was clutch." },
  "Emmanuel Sanders": { years: "2010–2021", team: "DEN", note: "Speed and professionalism on two Super Bowl rosters." },
  "Larry Fitzgerald": { years: "2004–2020", team: "ARI", note: "Gentleman assassin. Seventeen seasons, one franchise, Hall tape." },
  "Jordy Nelson": { years: "2008–2018", team: "GB", note: "Go ball. Lambeau leap. A Packers deep threat for a decade." },
  "Alshon Jeffery": { years: "2012–2020", team: "CHI", note: "Body-catch specialist. Bears star, then a championship in Philly." },
  "Tyler Boyd": { years: "2016–present", team: "CIN" },
  "Hunter Renfrow": { years: "2019–present", team: "LV" },
  "Christian Kirk": { years: "2018–present", team: "ARI" },
  "Allen Robinson": { years: "2014–present", team: "JAX", note: "Contested-catch WR1 on offenses that rarely helped." },
  "Will Fuller": { years: "2016–2021", team: "HOU" },
  "Randall Cobb": { years: "2011–2023", team: "GB", note: "Slot institution next to Nelson and Adams." },
  "Calvin Ridley": { years: "2018–present", team: "ATL" },
  "Jerry Jeudy": { years: "2020–present", team: "DEN" },
  "Marquise Brown": { years: "2019–present", team: "BAL" },
  "Doug Baldwin": { years: "2011–2018", team: "SEA", note: "Slot tough. Super Bowl hands in the Legion years." },
  "Golden Tate": { years: "2010–2020", team: "SEA", note: "YAC chaos. A WR1 in Seattle and Detroit." },
  "Marvin Jones": { years: "2012–2022", team: "CIN" },
  "Sammy Watkins": { years: "2014–2022", team: "BUF", note: "First-round speed. Super Bowl snaps in Kansas City." },
  "DeSean Jackson": { years: "2008–2022", team: "PHI", note: "Go-ball king who never lost the 4.3." },
  "Sterling Shepard": { years: "2016–present", team: "NYG" },
  "Corey Davis": { years: "2017–2022", team: "TEN" },
  "D.J. Chark": { years: "2018–present", team: "JAX" },
  "Nelson Agholor": { years: "2015–present", team: "PHI" },
  "Mohamed Sanu": { years: "2012–2021", team: "CIN" },
  "Cole Beasley": { years: "2012–2022", team: "DAL", note: "Slot technician in Dallas, then an Allen huddle in Buffalo." },
  "Jamison Crowder": { years: "2015–present", team: "WAS" },
  "Mecole Hardman": { years: "2019–present", team: "KC" },
  "DeVante Parker": { years: "2015–2022", team: "MIA" },
  "Curtis Samuel": { years: "2017–present", team: "CAR" },
  "Robby Anderson": { years: "2016–2023", team: "NYJ" },
  "Kenny Golladay": { years: "2017–2022", team: "DET" },
  "Jauan Jennings": { years: "2021–present", team: "SF" },
  "Jakobi Meyers": { years: "2019–present", team: "NE" },
  "Michael Pittman Jr.": { years: "2020–present", team: "IND" },
  "Darius Slayton": { years: "2019–present", team: "NYG" },
  "Tim Patrick": { years: "2018–present", team: "DEN" },
  "Van Jefferson": { years: "2020–present", team: "LAR" },
  "Travis Kelce": { years: "2013–present", team: "KC", note: "The position, rewritten. Super Bowl engine and a 1,300-yard peak." },
  "Rob Gronkowski": { years: "2010–2021", team: "NE", teams: ["NE", "TB"], note: "Matchup nightmare, blocking hammer, four rings, one un-retirement." },
  "George Kittle": { years: "2017–present", team: "SF" },
  "Mark Andrews": { years: "2018–present", team: "BAL" },
  "Greg Olsen": { years: "2007–2020", team: "CAR", note: "Cam's security blanket. Three 1,000-yard years in Carolina." },
  "Trey McBride": { years: "2022–present", team: "ARI" },
  "Brock Bowers": { years: "2024–present", team: "LV" },
  "Zach Ertz": { years: "2013–present", team: "PHI", teams: ["PHI", "ARI"], note: "Philly Special catch and a 116-catch season, then the encore." },
  "Sam LaPorta": { years: "2023–present", team: "DET" },
  "Darren Waller": { years: "2015–present", team: "LV", teams: ["LV", "NYG"], note: "Comeback story and a 1,100-yard WR-in-disguise." },
  "T.J. Hockenson": { years: "2019–present", team: "DET", teams: ["DET", "MIN"] },
  "Dallas Goedert": { years: "2018–present", team: "PHI" },
  "David Njoku": { years: "2017–present", team: "CLE" },
  "Evan Engram": { years: "2017–present", team: "NYG" },
  "Jimmy Graham": { years: "2010–2023", team: "NO", note: "Red-zone mismatch. Saints peak, then the long second act." },
  "Jason Witten": { years: "2003–2020", team: "DAL", note: "Iron man over the middle. A Cowboys career that spanned eras." },
  "Antonio Gates": { years: "2003–2018", team: "LAC", note: "Undrafted basketball body. The red-zone cheat code for sixteen years." },
  "Dalton Kincaid": { years: "2023–present", team: "BUF" },
  "Tucker Kraft": { years: "2023–present", team: "GB" },
  "Jake Ferguson": { years: "2022–present", team: "DAL" },
  "Dalton Schultz": { years: "2018–present", team: "DAL" },
  "Kyle Pitts": { years: "2021–present", team: "ATL" },
  "Isaiah Likely": { years: "2022–present", team: "BAL" },
  "Cole Kmet": { years: "2020–present", team: "CHI" },
  "Pat Freiermuth": { years: "2021–present", team: "PIT" },
  "Noah Fant": { years: "2019–present", team: "DEN" },
  "Mike Gesicki": { years: "2018–present", team: "MIA" },
  "Tyler Higbee": { years: "2016–present", team: "LAR" },
  "Jonnu Smith": { years: "2017–present", team: "TEN" },
  "Dawson Knox": { years: "2019–present", team: "BUF" },
  "Hunter Henry": { years: "2016–present", team: "LAC" },
  "Cade Otton": { years: "2022–present", team: "TB" },
  "Tyler Conklin": { years: "2018–present", team: "MIN" },
  "Delanie Walker": { years: "2006–2020", team: "TEN", note: "1,000-yard mismatch in Tennessee after a 49ers apprenticeship." },
  "Jordan Reed": { years: "2013–2020", team: "WAS", note: "Route-running TE who could not stay on the field." },
  "Eric Ebron": { years: "2014–2021", team: "DET" },
  "Austin Hooper": { years: "2016–present", team: "ATL" },
  "Jack Doyle": { years: "2013–2021", team: "IND" },
  "Cameron Brate": { years: "2014–2022", team: "TB" },
  "Jared Cook": { years: "2009–2021", team: "TEN", note: "Move TE who popped from Tennessee to the Saints." },
  "Gerald Everett": { years: "2017–present", team: "LAR" },
  "Will Dissly": { years: "2018–present", team: "SEA" },
  "Juwan Johnson": { years: "2020–present", team: "NO" },
  "Chigoziem Okonkwo": { years: "2022–present", team: "TEN" },
};
