/* generated by scripts/build-elim-legacy.py — real nflverse K/D boards */
import type { TeamId } from "./types";

type Row = readonly [name: string, team: TeamId, ppr: number];

export const ELIM_LEGACY_KD: Record<number, { K: readonly Row[]; D: readonly Row[] }> = {
  2006: {
    K: [
      ["Robbie Gould", "CHI", 139.0],
      ["John Carney", "NO", 107.0],
      ["Jeff Reed", "PIT", 101.0],
      ["Stephen Gostkowski", "NE", 90.0],
      ["Sebastian Janikowski", "LV", 65.0],
    ],
    D: [
      ["Bears", "CHI", 219.0],
      ["Steelers", "PIT", 132.0],
      ["Falcons", "ATL", 113.0],
      ["Browns", "CLE", 98.0],
      ["Redskins", "WAS", 66.0],
    ],
  },
  2007: {
    K: [
      ["Mason Crosby", "GB", 145.0],
      ["Phil Dawson", "CLE", 118.0],
      ["Sebastian Janikowski", "LV", 105.0],
      ["John Kasay", "CAR", 95.0],
      ["John Carney", "KC", 58.0],
    ],
    D: [
      ["Chargers", "LAC", 174.0],
      ["Cowboys", "DAL", 131.0],
      ["Bengals", "CIN", 111.0],
      ["Chiefs", "KC", 97.0],
      ["Dolphins", "MIA", 74.0],
    ],
  },
  2008: {
    K: [
      ["Rob Bironas", "TEN", 136.0],
      ["Rian Lindell", "BUF", 123.0],
      ["Neil Rackers", "ARI", 116.0],
      ["Olindo Mare", "SEA", 103.0],
      ["Shayne Graham", "CIN", 74.0],
    ],
    D: [
      ["Ravens", "BAL", 171.0],
      ["Giants", "NYG", 135.0],
      ["Browns", "CLE", 105.0],
      ["Texans", "HOU", 85.0],
      ["Rams", "LAR", 49.0],
    ],
  },
  2009: {
    K: [
      ["David Akers", "PHI", 139.0],
      ["Mason Crosby", "GB", 116.0],
      ["Sebastian Janikowski", "LV", 97.0],
      ["Josh Scobee", "JAX", 88.0],
      ["Billy Cundiff", "BAL", 69.0],
    ],
    D: [
      ["Saints", "NO", 171.0],
      ["Vikings", "MIN", 127.0],
      ["Panthers", "CAR", 109.0],
      ["Browns", "CLE", 101.0],
      ["Rams", "LAR", 50.0],
    ],
  },
  2010: {
    K: [
      ["David Akers", "PHI", 144.0],
      ["Nick Folk", "NYJ", 116.0],
      ["John Kasay", "CAR", 102.0],
      ["Garrett Hartley", "NO", 95.0],
      ["Ryan Longwell", "MIN", 69.0],
    ],
    D: [
      ["Steelers", "PIT", 153.0],
      ["Chargers", "LAC", 122.0],
      ["Ravens", "BAL", 109.0],
      ["49ers", "SF", 97.0],
      ["Broncos", "DEN", 40.0],
    ],
  },
  2011: {
    K: [
      ["David Akers", "SF", 159.0],
      ["Billy Cundiff", "BAL", 124.0],
      ["Connor Barth", "TB", 108.0],
      ["Ryan Longwell", "MIN", 98.0],
      ["Josh Brown", "LAR", 78.0],
    ],
    D: [
      ["49ers", "SF", 169.0],
      ["Eagles", "PHI", 129.0],
      ["Jaguars", "JAX", 104.0],
      ["Raiders", "LV", 91.0],
      ["Colts", "IND", 69.0],
    ],
  },
  2012: {
    K: [
      ["Stephen Gostkowski", "NE", 150.0],
      ["Sebastian Janikowski", "LV", 126.0],
      ["Steven Hauschka", "SEA", 109.0],
      ["Rian Lindell", "BUF", 101.0],
      ["Justin Medlock", "CAR", 46.0],
    ],
    D: [
      ["Bears", "CHI", 189.0],
      ["Chargers", "LAC", 131.0],
      ["Rams", "LAR", 113.0],
      ["Cowboys", "DAL", 90.0],
      ["Chiefs", "KC", 46.0],
    ],
  },
  2013: {
    K: [
      ["Justin Tucker", "BAL", 152.0],
      ["Nick Novak", "LAC", 133.0],
      ["Shaun Suisham", "PIT", 121.0],
      ["Sebastian Janikowski", "LV", 104.0],
      ["Kai Forbath", "WAS", 67.0],
    ],
    D: [
      ["Chiefs", "KC", 198.0],
      ["Dolphins", "MIA", 116.0],
      ["Colts", "IND", 103.0],
      ["Steelers", "PIT", 91.0],
      ["Texans", "HOU", 63.0],
    ],
  },
  2014: {
    K: [
      ["Stephen Gostkowski", "NE", 155.0],
      ["Dan Bailey", "DAL", 129.0],
      ["Phil Dawson", "SF", 110.0],
      ["Josh Brown", "NYG", 97.0],
      ["Robbie Gould", "CHI", 58.0],
    ],
    D: [
      ["Eagles", "PHI", 172.0],
      ["Dolphins", "MIA", 125.0],
      ["Broncos", "DEN", 95.0],
      ["Bengals", "CIN", 83.0],
      ["Raiders", "LV", 46.0],
    ],
  },
  2015: {
    K: [
      ["Stephen Gostkowski", "NE", 158.0],
      ["Justin Tucker", "BAL", 123.0],
      ["Chris Boswell", "PIT", 113.0],
      ["Travis Coons", "CLE", 93.0],
      ["Andrew Franks", "MIA", 64.0],
    ],
    D: [
      ["Broncos", "DEN", 163.0],
      ["Eagles", "PHI", 119.0],
      ["Colts", "IND", 95.0],
      ["Bills", "BUF", 78.0],
      ["Chargers", "LAC", 59.0],
    ],
  },
};
