/* generated by scripts/build-elim-weeks.py — real Sleeper K/D boards */
import type { TeamId } from "./types";

type Row = readonly [name: string, team: TeamId, ppr: number];

export const ELIM_KD: Record<number, { K: readonly Row[]; D: readonly Row[] }> = {
  2016: {
    K: [
      ["Justin Tucker", "BAL", 159.0],
      ["Wil Lutz", "NO", 125.0],
      ["Stephen Gostkowski", "NE", 112.0],
      ["Phil Dawson", "SF", 87.0],
      ["Cody Parkey", "CLE", 69.0],
    ],
    D: [
      ["Chiefs", "KC", 159.0],
      ["Patriots", "NE", 127.0],
      ["Steelers", "PIT", 99.0],
      ["Texans", "HOU", 85.0],
      ["Browns", "CLE", 46.0],
    ],
  },
  2017: {
    K: [
      ["Greg Zuerlein", "LAR", 178.0],
      ["Harrison Butker", "KC", 130.0],
      ["Graham Gano", "CAR", 113.0],
      ["Giorgio Tavecchio", "LV", 76.0],
      ["Connor Barth", "CHI", 52.0],
    ],
    D: [
      ["Jaguars", "JAX", 208.0],
      ["Bears", "CHI", 125.0],
      ["Dolphins", "MIA", 100.0],
      ["Redskins", "WAS", 90.0],
      ["Raiders", "LV", 64.0],
    ],
  },
  2018: {
    K: [
      ["Ka'imi Fairbairn", "HOU", 150.0],
      ["Aldrick Rosas", "NYG", 119.0],
      ["Matt Prater", "DET", 102.0],
      ["Randy Bullock", "CIN", 86.0],
      ["Chandler Catanzaro", "CAR", 59.0],
    ],
    D: [
      ["Bears", "CHI", 187.0],
      ["Saints", "NO", 117.0],
      ["Browns", "CLE", 107.0],
      ["Chargers", "LAC", 89.0],
      ["Raiders", "LV", 37.0],
    ],
  },
  2019: {
    K: [
      ["Wil Lutz", "NO", 143.0],
      ["Greg Zuerlein", "LAR", 109.0],
      ["Brett Maher", "DAL", 95.0],
      ["Jake Elliott", "PHI", 88.0],
      ["Aldrick Rosas", "NYG", 57.0],
    ],
    D: [
      ["Patriots", "NE", 232.0],
      ["Bills", "BUF", 136.0],
      ["Packers", "GB", 103.0],
      ["Falcons", "ATL", 94.0],
      ["Dolphins", "MIA", 44.0],
    ],
  },
  2020: {
    K: [
      ["Younghoe Koo", "ATL", 153.0],
      ["Joey Slye", "CAR", 117.0],
      ["Wil Lutz", "NO", 110.0],
      ["Matt Prater", "DET", 100.0],
      ["Jake Elliott", "PHI", 61.0],
    ],
    D: [
      ["Dolphins", "MIA", 148.0],
      ["Eagles", "PHI", 106.0],
      ["Bears", "CHI", 95.0],
      ["Cowboys", "DAL", 71.0],
      ["Lions", "DET", 42.0],
    ],
  },
  2021: {
    K: [
      ["Matt Gay", "LAR", 148.0],
      ["Jake Elliott", "PHI", 128.0],
      ["Ryan Succop", "TB", 111.0],
      ["Robbie Gould", "SF", 87.0],
      ["Matt Ammendola", "NYJ", 48.0],
    ],
    D: [
      ["Cowboys", "DAL", 184.0],
      ["Cardinals", "ARI", 127.0],
      ["Rams", "LAR", 107.0],
      ["Seahawks", "SEA", 84.0],
      ["Jaguars", "JAX", 54.0],
    ],
  },
  2022: {
    K: [
      ["Brett Maher", "DAL", 146.0],
      ["Younghoe Koo", "ATL", 122.0],
      ["Robbie Gould", "SF", 115.0],
      ["Joey Slye", "WAS", 96.0],
      ["Randy Bullock", "TEN", 64.0],
    ],
    D: [
      ["Patriots", "NE", 178.0],
      ["Cardinals", "ARI", 106.0],
      ["Broncos", "DEN", 99.0],
      ["Texans", "HOU", 94.0],
      ["Bears", "CHI", 64.0],
    ],
  },
  2023: {
    K: [
      ["Brandon Aubrey", "DAL", 157.0],
      ["Matt Gay", "IND", 126.0],
      ["Blake Grupe", "NO", 119.0],
      ["Anders Carlson", "GB", 102.0],
      ["Chad Ryland", "NE", 66.0],
    ],
    D: [
      ["Cowboys", "DAL", 166.0],
      ["Steelers", "PIT", 138.0],
      ["Texans", "HOU", 113.0],
      ["Patriots", "NE", 104.0],
      ["Panthers", "CAR", 59.0],
    ],
  },
  2024: {
    K: [
      ["Chris Boswell", "PIT", 177.0],
      ["Chase McLaughlin", "TB", 137.0],
      ["Matt Gay", "IND", 110.0],
      ["Jake Moody", "SF", 99.0],
      ["Dustin Hopkins", "CLE", 65.0],
    ],
    D: [
      ["Broncos", "DEN", 161.0],
      ["Eagles", "PHI", 119.0],
      ["Cardinals", "ARI", 98.0],
      ["Commanders", "WAS", 90.0],
      ["Panthers", "CAR", 50.0],
    ],
  },
  2025: {
    K: [
      ["Jason Myers", "SEA", 179.0],
      ["Chris Boswell", "PIT", 129.0],
      ["Cairo Santos", "CHI", 119.0],
      ["Blake Grupe", "IND", 102.0],
      ["Daniel Carlson", "LV", 76.0],
    ],
    D: [
      ["Seahawks", "SEA", 158.0],
      ["Bills", "BUF", 111.0],
      ["Colts", "IND", 100.0],
      ["49ers", "SF", 84.0],
      ["Cowboys", "DAL", 58.0],
    ],
  },
};
