import type { Player, Position, TeamId } from "./types";
import { CAREER } from "./career";
import { applyBestSeason } from "./ratings";
import { teamById } from "./teams";

type Row = [string, string, Position, TeamId, string, string, number, string];

const ROWS: Row[] = [
  // Career pool: one card per name, and only if they took an NFL snap in 2016 or later.
  // Years and signature teams are applied in CAREER.
  ["mahomes", "Patrick Mahomes", "QB", "KC", "Kansas City Chiefs", "2017–present", 97, "No-look dimes and a growing ring count."],
  ["brady-tb", "Tom Brady", "QB", "TB", "Tampa Bay Buccaneers", "2020–2022", 96, "The seventh ring, taken in Tampa at forty-three."],
  ["eli", "Eli Manning", "QB", "NYG", "New York Giants", "2004–2019", 84, "Two Super Bowl MVPs. Brady's problem in February."],
  ["rg3", "Robert Griffin III", "QB", "WAS", "Washington", "2012–2020", 87, "Rookie-year electricity. Zone-read lightning until the knee."],
  ["palmer", "Carson Palmer", "QB", "ARI", "Arizona Cardinals", "2003–2017", 86, "Bengals cannon, then a Cardinals rebirth that nearly went all the way."],
  ["arod", "Aaron Rodgers", "QB", "GB", "Green Bay Packers", "2016–2022", 95, "Four MVPs and the coldest sideline stare in Wisconsin."],
  ["jallen", "Josh Allen", "QB", "BUF", "Buffalo Bills", "2018–present", 95, "Cannon arm, truck-stick legs, perpetual AFC threat."],
  ["lamar", "Lamar Jackson", "QB", "BAL", "Baltimore Ravens", "2018–present", 94, "Dual-threat MVP who broke the position's geometry."],
  ["brees", "Drew Brees", "QB", "NO", "New Orleans Saints", "2016–2020", 93, "Late-career accuracy that still moved the record book."],
  ["burrow", "Joe Burrow", "QB", "CIN", "Cincinnati Bengals", "2020–present", 92, "Coolest customer in stripes. Super Bowl trip included."],
  ["rwilson", "Russell Wilson", "QB", "SEA", "Seattle Seahawks", "2016–2021", 90, "Scramble-drill king of the Legion of Boom twilight."],
  ["bigben", "Ben Roethlisberger", "QB", "PIT", "Pittsburgh Steelers", "2016–2021", 88, "Extender of plays until the very last snap."],
  ["stafford", "Matthew Stafford", "QB", "LAR", "Los Angeles Rams", "2021–present", 88, "Detroit warrior who cashed a ring in L.A."],
  ["herbert", "Justin Herbert", "QB", "LAC", "Los Angeles Chargers", "2020–present", 89, "Prototype arm talent still hunting a deep run."],
  ["hurts", "Jalen Hurts", "QB", "PHI", "Philadelphia Eagles", "2020–present", 88, "Tush-push emperor and Super Bowl starter."],
  ["mryan", "Matt Ryan", "QB", "ATL", "Atlanta Falcons", "2016–2021", 88, "2016 MVP. That lead still haunts a city."],
  ["rivers", "Philip Rivers", "QB", "LAC", "Los Angeles Chargers", "2016–2020", 86, "Sideline sermonizer with 400-yard Sundays."],
  ["luck", "Andrew Luck", "QB", "IND", "Indianapolis Colts", "2016–2018", 87, "Generational talent who walked away too soon."],
  ["dak", "Dak Prescott", "QB", "DAL", "Dallas Cowboys", "2016–present", 86, "Star on the helmet, January still the question."],
  ["goff", "Jared Goff", "QB", "DET", "Detroit Lions", "2021–present", 86, "Reborn in Detroit after the Rams moved on."],
  ["jdaniells", "Jayden Daniels", "QB", "WAS", "Washington Commanders", "2024–present", 85, "Rookie dynamite that dragged Washington to January."],
  ["stroud", "C.J. Stroud", "QB", "HOU", "Houston Texans", "2023–present", 85, "Rookie-year opera in a rebuilding huddle."],
  ["purdy", "Brock Purdy", "QB", "SF", "San Francisco 49ers", "2022–present", 85, "Mr. Irrelevant who kept the dynasty humming."],
  ["watson", "Deshaun Watson", "QB", "HOU", "Houston Texans", "2017–2020", 86, "Houston peak: scramble, throw, and take over games."],
  ["cam", "Cam Newton", "QB", "CAR", "Carolina Panthers", "2016–2019", 84, "Superman fading, still a problem in the red zone."],
  ["jlove", "Jordan Love", "QB", "GB", "Green Bay Packers", "2023–present", 84, "The man who inherited 12 and didn't blink."],
  ["cousins", "Kirk Cousins", "QB", "MIN", "Minnesota Vikings", "2018–2023", 84, "Fully guaranteed and fully competent."],
  ["kyler", "Kyler Murray", "QB", "ARI", "Arizona Cardinals", "2019–present", 84, "Compact dynamite when the legs are healthy."],
  ["tua", "Tua Tagovailoa", "QB", "MIA", "Miami Dolphins", "2020–present", 83, "Rhythm passer in a speed-skill circus."],
  ["lawrence", "Trevor Lawrence", "QB", "JAX", "Jacksonville Jaguars", "2021–present", 82, "Can't-miss prospect, still becoming the guy."],
  ["carr", "Derek Carr", "QB", "LV", "Las Vegas Raiders", "2016–2022", 83, "Silver-and-black starter with a cannon and a conscience."],
  ["wentz", "Carson Wentz", "QB", "PHI", "Philadelphia Eagles", "2016–2018", 87, "MVP-track 2017 before the knee changed everything."],
  ["tannehill", "Ryan Tannehill", "QB", "TEN", "Tennessee Titans", "2019–2022", 84, "The Titans bloom: play-action king next to Henry."],
  ["geno", "Geno Smith", "QB", "SEA", "Seattle Seahawks", "2022–present", 84, "Comeback QB of the Year after a long wilderness."],
  ["baker", "Baker Mayfield", "QB", "TB", "Tampa Bay Buccaneers", "2023–present", 83, "Second-act starter who dragged Tampa back to January."],
  ["nix", "Bo Nix", "QB", "DEN", "Denver Broncos", "2024–present", 82, "Rookie-year composure in a rebuilt Denver."],
  ["caleb", "Caleb Williams", "QB", "CHI", "Chicago Bears", "2024–present", 81, "First-overall live arm in a new Chicago."],
  ["maye", "Drake Maye", "QB", "NE", "New England Patriots", "2024–present", 83, "Patriot rebuild's best look in a decade."],

  // Running backs
  ["cmc", "Christian McCaffrey", "RB", "SF", "San Francisco 49ers", "2017–present", 94, "Swiss-army back who later won a ring in scarlet."],
  ["cj2k", "Chris Johnson", "RB", "TEN", "Tennessee Titans", "2008–2017", 95, "2,006 rushing yards. The 4.24 that defenses never caught."],
  ["foster", "Arian Foster", "RB", "HOU", "Houston Texans", "2009–2016", 95, "Undrafted zone-scheme king. 1,600 and 16 as a first-year starter."],
  ["jcharles", "Jamaal Charles", "RB", "KC", "Kansas City Chiefs", "2008–2018", 94, "5.4 a carry and receiving chops. The Chiefs' home-run threat."],
  ["beastmode", "Marshawn Lynch", "RB", "SEA", "Seattle Seahawks", "2007–2019", 90, "Beast Mode. Legion of Boom closer and a Super Bowl run."],
  ["henry", "Derrick Henry", "RB", "TEN", "Tennessee Titans", "2016–2023", 94, "King Henry. Trucks, stiff-arms, 2,000-yard thunder."],
  ["saquon", "Saquon Barkley", "RB", "PHI", "Philadelphia Eagles", "2018–present", 91, "Generational talent who exploded again in Philly."],
  ["kamara", "Alvin Kamara", "RB", "NO", "New Orleans Saints", "2017–present", 89, "Pass-catching nightmare out of the slot or backfield."],
  ["chubb", "Nick Chubb", "RB", "CLE", "Cleveland Browns", "2018–present", 89, "One-cut violence. Film-room favorite."],
  ["lbell", "Le'Veon Bell", "RB", "PIT", "Pittsburgh Steelers", "2016–2017", 90, "The pause. Patient, violent, complete."],
  ["jtaylor", "Jonathan Taylor", "RB", "IND", "Indianapolis Colts", "2020–present", 88, "2021 rushing champ. Home-run gear still intact."],
  ["gurley", "Todd Gurley", "RB", "LAR", "Los Angeles Rams", "2016–2019", 90, "Offensive Player of the Year — until the knee said no."],
  ["gibbs", "Jahmyr Gibbs", "RB", "DET", "Detroit Lions", "2023–present", 88, "Slot-back hybrid who scores from anywhere."],
  ["bijan", "Bijan Robinson", "RB", "ATL", "Atlanta Falcons", "2023–present", 87, "Three-down prospect who looks the part."],
  ["shady", "LeSean McCoy", "RB", "BUF", "Buffalo Bills", "2016–2019", 86, "Make-you-miss specialist in a Bills backfield."],
  ["zeke", "Ezekiel Elliott", "RB", "DAL", "Dallas Cowboys", "2016–2022", 88, "Bell-cow with a rushing crown as a rookie."],
  ["dalvin", "Dalvin Cook", "RB", "MIN", "Minnesota Vikings", "2017–2022", 87, "Vision and burst until the mileage showed."],
  ["jacobs", "Josh Jacobs", "RB", "LV", "Las Vegas Raiders", "2019–present", 86, "Between-the-tackles king. Rushing-title season."],
  ["breece", "Breece Hall", "RB", "NYJ", "New York Jets", "2022–present", 86, "Explosive after a rookie ACL. Still a problem."],
  ["ajones", "Aaron Jones", "RB", "GB", "Green Bay Packers", "2017–2023", 85, "Burst, receiving chops, Lambeau winters."],
  ["achane", "De'Von Achane", "RB", "MIA", "Miami Dolphins", "2023–present", 85, "4.3 speed in a jet-offense laboratory."],
  ["ekeler", "Austin Ekeler", "RB", "LAC", "Los Angeles Chargers", "2017–2023", 87, "PPR cheat code out of the backfield."],
  ["mixon", "Joe Mixon", "RB", "CIN", "Cincinnati Bengals", "2017–2023", 84, "Between-tackle finisher on a Super Bowl roster."],
  ["kyren", "Kyren Williams", "RB", "LAR", "Los Angeles Rams", "2022–present", 85, "Contact balance and a sudden 1,000-yard leap."],
  ["conner", "James Conner", "RB", "ARI", "Arizona Cardinals", "2017–present", 83, "Goal-line hammer who outlasted the doubters."],
  ["hunt", "Kareem Hunt", "RB", "KC", "Kansas City Chiefs", "2017–2018", 86, "Rookie rushing champ in a Super Bowl backfield."],
  ["ingram", "Mark Ingram", "RB", "NO", "New Orleans Saints", "2016–2018", 84, "Between-tackle partner to Kamara's chaos."],
  ["freeman", "Devonta Freeman", "RB", "ATL", "Atlanta Falcons", "2016–2018", 85, "Zone-scheme scorer on a Super Bowl roster."],
  ["gordon-melvin", "Melvin Gordon", "RB", "LAC", "Los Angeles Chargers", "2016–2019", 83, "Committee king with red-zone gravity."],
  ["howard-jordan", "Jordan Howard", "RB", "CHI", "Chicago Bears", "2016–2018", 83, "Rookie 1,300-yard hammer in Chicago."],
  ["carson", "Chris Carson", "RB", "SEA", "Seattle Seahawks", "2017–2021", 84, "North-south bruiser behind a zone line."],
  ["mack", "Marlon Mack", "RB", "IND", "Indianapolis Colts", "2017–2020", 82, "One-cut speed when the Colts line opened."],
  ["fournette", "Leonard Fournette", "RB", "TB", "Tampa Bay Buccaneers", "2020–2022", 84, "Super Bowl closer after the Jacksonville chapter."],
  ["djohnson", "David Johnson", "RB", "ARI", "Arizona Cardinals", "2016–2018", 88, "All-purpose monster before the injury fog."],
  ["djmoore-rb", "David Montgomery", "RB", "CHI", "Chicago Bears", "2019–present", 84, "Contact balance and a Lions-year leap."],
  ["kwalker", "Kenneth Walker III", "RB", "SEA", "Seattle Seahawks", "2022–present", 84, "Cut-on-a-dime home-run threat."],
  ["jcook", "James Cook", "RB", "BUF", "Buffalo Bills", "2022–present", 85, "Receiving back with a rushing-title sniff."],
  ["pacheco", "Isiah Pacheco", "RB", "KC", "Kansas City Chiefs", "2022–present", 83, "Seventh-round hammer on a dynasty."],
  ["swift", "D'Andre Swift", "RB", "PHI", "Philadelphia Eagles", "2020–present", 82, "Elusive changer of direction in a new city."],
  ["pollard", "Tony Pollard", "RB", "DAL", "Dallas Cowboys", "2019–2023", 84, "The other Cowboy who became the lead."],
  ["najee", "Najee Harris", "RB", "PIT", "Pittsburgh Steelers", "2021–2024", 83, "Volume back. Yards after contact."],
  ["etienne", "Travis Etienne", "RB", "JAX", "Jacksonville Jaguars", "2021–present", 84, "Speed and screens in Doug's offense."],
  ["dobbins", "J.K. Dobbins", "RB", "BAL", "Baltimore Ravens", "2020–present", 83, "Explosive when the knees allowed it."],
  ["singletary", "Devin Singletary", "RB", "BUF", "Buffalo Bills", "2019–2022", 81, "Patient zone runner with receiving chops."],
  ["sanders", "Miles Sanders", "RB", "PHI", "Philadelphia Eagles", "2019–2022", 82, "Outside-zone home runs on a Super Bowl roster."],
  ["jwilliams-rb", "Javonte Williams", "RB", "DEN", "Denver Broncos", "2021–present", 82, "Contact balance that survived a torn knee."],
  ["rstevenson", "Rhamondre Stevenson", "RB", "NE", "New England Patriots", "2021–present", 83, "Big back with surprisingly soft hands."],
  ["irving", "Bucky Irving", "RB", "TB", "Tampa Bay Buccaneers", "2024–present", 85, "Rookie vision and burst in Tampa."],
  ["jeanty", "Ashton Jeanty", "RB", "LV", "Las Vegas Raiders", "2025–present", 84, "Workhorse prospect with between-tackle violence."],
  ["charbs", "Zach Charbonnet", "RB", "SEA", "Seattle Seahawks", "2023–present", 81, "Between-tackle complement with receiving work."],
  ["drake", "Kenyan Drake", "RB", "ARI", "Arizona Cardinals", "2019–2021", 83, "Monday-night walk-off and a 1,000-yard year."],
  ["aj-dillon", "A.J. Dillon", "RB", "GB", "Green Bay Packers", "2020–2023", 82, "Short-yardage tank with surprising juice."],
  ["robinson-brian", "Brian Robinson Jr.", "RB", "WAS", "Washington Commanders", "2022–present", 83, "Between-tackle lead who would not stay down."],
  ["hubbard", "Chuba Hubbard", "RB", "CAR", "Carolina Panthers", "2021–present", 84, "Workhorse who finally got the keys."],

  // Wide receivers
  ["jjett", "Justin Jefferson", "WR", "MIN", "Minnesota Vikings", "2020–present", 96, "The new film-room standard. Contested-catch artist."],
  ["ssmith", "Steve Smith", "WR", "CAR", "Carolina Panthers", "2001–2016", 93, "Undrafted fire. 1,563 yards and a chip on both shoulders."],
  ["andjohnson", "Andre Johnson", "WR", "HOU", "Houston Texans", "2003–2016", 92, "Contested-catch king on offenses that rarely had a quarterback."],
  ["bmarshall", "Brandon Marshall", "WR", "DEN", "Denver Broncos", "2006–2018", 93, "Volume king. A 1,500-yard year in Chicago and another in New York."],
  ["jgordon", "Josh Gordon", "WR", "CLE", "Cleveland Browns", "2012–2023", 91, "1,646 yards in ten games' worth of magic. The 2013 Browns year."],
  ["boldin", "Anquan Boldin", "WR", "ARI", "Arizona Cardinals", "2003–2016", 90, "Rookie explosion, then a career of contested catches and rings."],
  ["chase", "Ja'Marr Chase", "WR", "CIN", "Cincinnati Bengals", "2021–present", 95, "Burrow's answer. YAC chaos in stripes."],
  ["adams", "Davante Adams", "WR", "GB", "Green Bay Packers", "2016–2021", 94, "The release. Rodgers' favorite money throw."],
  ["julio", "Julio Jones", "WR", "ATL", "Atlanta Falcons", "2016–2020", 93, "Uncoverable in his prime. Body eventually billed him."],
  ["tyreek", "Tyreek Hill", "WR", "MIA", "Miami Dolphins", "2016–present", 93, "Cheetah. Changed the math of a defense's leverage."],
  ["abrown", "Antonio Brown", "WR", "PIT", "Pittsburgh Steelers", "2016–2018", 93, "Route-running savant. The exit was a circus."],
  ["hopkins", "DeAndre Hopkins", "WR", "HOU", "Houston Texans", "2016–2019", 92, "Nuk. Hands that ignore coverage."],
  ["evans", "Mike Evans", "WR", "TB", "Tampa Bay Buccaneers", "2016–present", 90, "1,000 yards every. single. season."],
  ["kupp", "Cooper Kupp", "WR", "LAR", "Los Angeles Rams", "2017–present", 91, "Triple Crown and a Super Bowl MVP."],
  ["ajbrown", "A.J. Brown", "WR", "PHI", "Philadelphia Eagles", "2019–present", 90, "Body control and contested-catch violence."],
  ["lamb", "CeeDee Lamb", "WR", "DAL", "Dallas Cowboys", "2020–present", 90, "Cowboys' new WR1. Yards after the catch for days."],
  ["diggs", "Stefon Diggs", "WR", "BUF", "Buffalo Bills", "2016–present", 89, "Minneapolis Miracle origin, Buffalo peak."],
  ["mthomas", "Michael Thomas", "WR", "NO", "New Orleans Saints", "2016–2021", 90, "Record 149 catches. Then the injury spiral."],
  ["keenan", "Keenan Allen", "WR", "LAC", "Los Angeles Chargers", "2016–2023", 88, "Option-route professor. Always open."],
  ["arsb", "Amon-Ra St. Brown", "WR", "DET", "Detroit Lions", "2021–present", 89, "Slot assassin. Detroit's chain-mover."],
  ["ajgreen", "A.J. Green", "WR", "CIN", "Cincinnati Bengals", "2016–2020", 87, "Prototype X. Quiet, huge, consistent."],
  ["obj", "Odell Beckham Jr.", "WR", "NYG", "New York Giants", "2016–2018", 88, "The Catch. Then the circus."],
  ["dk", "DK Metcalf", "WR", "SEA", "Seattle Seahawks", "2019–present", 86, "Combine freak who actually played like one."],
  ["dez", "Dez Bryant", "WR", "DAL", "Dallas Cowboys", "2016–2017", 85, "Was it a catch? The production was."],
  ["dthomas", "Demaryius Thomas", "WR", "DEN", "Denver Broncos", "2016–2017", 85, "YAC king of the Manning Broncos twilight."],
  ["puka", "Puka Nacua", "WR", "LAR", "Los Angeles Rams", "2023–present", 88, "Fifth-rounder who rewrote rookie records."],
  ["nico", "Nico Collins", "WR", "HOU", "Houston Texans", "2021–present", 87, "Stroud's big-bodied answer."],
  ["nabers", "Malik Nabers", "WR", "NYG", "New York Giants", "2024–present", 87, "Rookie-year monster. The tape pops."],
  ["deebo", "Deebo Samuel", "WR", "SF", "San Francisco 49ers", "2019–present", 86, "Wide back. Running-back snaps included."],
  ["waddle", "Jaylen Waddle", "WR", "MIA", "Miami Dolphins", "2021–present", 85, "Acceleration in the Tua rhythm offense."],
  ["hilton", "T.Y. Hilton", "WR", "IND", "Indianapolis Colts", "2016–2021", 85, "The Ghost. Deep threat on a weekly basis."],
  ["amari", "Amari Cooper", "WR", "DAL", "Dallas Cowboys", "2016–present", 86, "Route polish. A WR1 in two cities."],
  ["godwin", "Chris Godwin", "WR", "TB", "Tampa Bay Buccaneers", "2017–present", 86, "YAC technician next to Evans."],
  ["lockett", "Tyler Lockett", "WR", "SEA", "Seattle Seahawks", "2016–2024", 85, "Sure hands, better vibes, yearly 1,000."],
  ["djmoore", "DJ Moore", "WR", "CHI", "Chicago Bears", "2018–present", 86, "WR1 on teams that rarely had a QB1."],
  ["gwilson", "Garrett Wilson", "WR", "NYJ", "New York Jets", "2022–present", 86, "Separation artist waiting on a quarterback."],
  ["thielen", "Adam Thielen", "WR", "MIN", "Minnesota Vikings", "2016–2022", 85, "Undrafted Minnesotan who became a star."],
  ["higgins", "Tee Higgins", "WR", "CIN", "Cincinnati Bengals", "2020–present", 87, "Boundary X with a catch radius that swallows DBs."],
  ["aiyuk", "Brandon Aiyuk", "WR", "SF", "San Francisco 49ers", "2020–present", 86, "YAC and releases in Shanahan's lab."],
  ["olave", "Chris Olave", "WR", "NO", "New Orleans Saints", "2022–present", 84, "Sudden separation from the slot or boundary."],
  ["london", "Drake London", "WR", "ATL", "Atlanta Falcons", "2022–present", 86, "Big-bodied chain mover in Atlanta."],
  ["btj", "Brian Thomas Jr.", "WR", "JAX", "Jacksonville Jaguars", "2024–present", 87, "Rookie deep threat with WR1 production."],
  ["mhj", "Marvin Harrison Jr.", "WR", "ARI", "Arizona Cardinals", "2024–present", 83, "The name, the size, the pedigree."],
  ["flowers", "Zay Flowers", "WR", "BAL", "Baltimore Ravens", "2023–present", 85, "Slot dynamite in a Lamar offense."],
  ["rice", "Rashee Rice", "WR", "KC", "Kansas City Chiefs", "2023–present", 86, "YAC machine next to Kelce."],
  ["pickens", "George Pickens", "WR", "PIT", "Pittsburgh Steelers", "2022–present", 85, "Contested-catch artist with a flair for the sideline."],
  ["smith-devonta", "DeVonta Smith", "WR", "PHI", "Philadelphia Eagles", "2021–present", 86, "Slight frame, uncoverable releases."],
  ["sutton", "Courtland Sutton", "WR", "DEN", "Denver Broncos", "2018–present", 84, "Jump-ball X who waited out the QB carousel."],
  ["mclaurin", "Terry McLaurin", "WR", "WAS", "Washington Commanders", "2019–present", 86, "Scary Terry. Production without a QB, then with one."],
  ["diontae", "Diontae Johnson", "WR", "PIT", "Pittsburgh Steelers", "2019–2023", 84, "Release artist with 100-target gravity."],
  ["juju", "JuJu Smith-Schuster", "WR", "PIT", "Pittsburgh Steelers", "2017–2021", 83, "YAC over the middle on a Super Bowl-adjacent roster."],
  ["cooks", "Brandin Cooks", "WR", "NE", "New England Patriots", "2017–present", 84, "Deep threat who produced in five cities."],
  ["woods", "Robert Woods", "WR", "LAR", "Los Angeles Rams", "2017–2021", 83, "The other Ram. Chain mover and blocker."],
  ["landry", "Jarvis Landry", "WR", "CLE", "Cleveland Browns", "2016–2021", 84, "Sun in my eyes. Slot volume king."],
  ["edelman", "Julian Edelman", "WR", "NE", "New England Patriots", "2016–2020", 85, "Slot tough. Super Bowl MVP."],
  ["sanders-emmanuel", "Emmanuel Sanders", "WR", "DEN", "Denver Broncos", "2016–2019", 83, "Speed and professionalism on two Super Bowl rosters."],
  ["fitzgerald", "Larry Fitzgerald", "WR", "ARI", "Arizona Cardinals", "2016–2020", 86, "Gentleman assassin in the late desert years."],
  ["jordy", "Jordy Nelson", "WR", "GB", "Green Bay Packers", "2016–2017", 85, "Go ball. Lambeau leap."],
  ["jeffery", "Alshon Jeffery", "WR", "PHI", "Philadelphia Eagles", "2017–2019", 82, "Body-catch specialist on a championship roster."],
  ["boyd", "Tyler Boyd", "WR", "CIN", "Cincinnati Bengals", "2016–2023", 82, "Slot glue in a Super Bowl offense."],
  ["renfrow", "Hunter Renfrow", "WR", "LV", "Las Vegas Raiders", "2019–2023", 82, "PPR slot who led the league in slot snaps."],
  ["kirk", "Christian Kirk", "WR", "JAX", "Jacksonville Jaguars", "2018–present", 83, "Slot money in a new Jags contract."],
  ["robinson-allen", "Allen Robinson", "WR", "CHI", "Chicago Bears", "2018–2021", 85, "Contested-catch WR1 on bad offenses."],
  ["fuller", "Will Fuller", "WR", "HOU", "Houston Texans", "2016–2020", 83, "Deep threat who cooked when healthy."],
  ["cobb", "Randall Cobb", "WR", "GB", "Green Bay Packers", "2016–2018", 82, "Slot institution next to Adams."],
  ["adams-davante-lv", "Davante Adams", "WR", "LV", "Las Vegas Raiders", "2022–2024", 90, "The release, transplanted to silver and black."],
  ["hill-kc", "Tyreek Hill", "WR", "KC", "Kansas City Chiefs", "2016–2021", 93, "Cheetah in red. Super Bowl speed."],
  ["hopkins-ari", "DeAndre Hopkins", "WR", "ARI", "Arizona Cardinals", "2020–2022", 88, "Nuk in the desert. Still uncoverable."],
  ["adams-nyj", "Davante Adams", "WR", "NYJ", "New York Jets", "2024–present", 86, "Veteran X still winning at the stem."],
  ["evans-prime", "Mike Evans", "WR", "TB", "Tampa Bay Buccaneers", "2016–2019", 90, "The 1,000-yard machine in its first decade."],
  ["jamo", "Jameson Williams", "WR", "DET", "Detroit Lions", "2022–present", 83, "Vertical juice in a Lions explosion."],
  ["reed-jayden", "Jayden Reed", "WR", "GB", "Green Bay Packers", "2023–present", 83, "Gadget and slot scorer in Love's offense."],
  ["doubs", "Romeo Doubs", "WR", "GB", "Green Bay Packers", "2022–present", 81, "Boundary reliability in Green Bay."],
  ["watson-christian", "Christian Watson", "WR", "GB", "Green Bay Packers", "2022–present", 82, "4.3 and a red-zone leap."],
  ["worthy", "Xavier Worthy", "WR", "KC", "Kansas City Chiefs", "2024–present", 83, "Combine-record speed in a Super Bowl offense."],
  ["odunze", "Rome Odunze", "WR", "CHI", "Chicago Bears", "2024–present", 83, "Big-bodied rookie with WR1 tools."],
  ["btj2", "Ladd McConkey", "WR", "LAC", "Los Angeles Chargers", "2024–present", 86, "Slot technician as a rookie."],
  ["coker", "Keon Coleman", "WR", "BUF", "Buffalo Bills", "2024–present", 81, "Contested-catch size in Buffalo."],
  ["downs", "Josh Downs", "WR", "IND", "Indianapolis Colts", "2023–present", 83, "Slot separation as a rookie and beyond."],
  ["addison", "Jordan Addison", "WR", "MIN", "Minnesota Vikings", "2023–present", 84, "The other Viking with vertical juice."],
  ["qjohnston", "Quentin Johnston", "WR", "LAC", "Los Angeles Chargers", "2023–present", 81, "Size and a second-year leap."],
  ["jsn", "Jaxon Smith-Njigba", "WR", "SEA", "Seattle Seahawks", "2023–present", 87, "Slot savant in Seattle."],
  ["zflowers", "Rashid Shaheed", "WR", "NO", "New Orleans Saints", "2022–present", 82, "Track speed that became a weekly bomb."],
  ["dell", "Tank Dell", "WR", "HOU", "Houston Texans", "2023–present", 83, "Undersized deep threat with WR1 weeks."],
  ["parker", "DeVante Parker", "WR", "MIA", "Miami Dolphins", "2016–2021", 82, "Body-catch X with a 1,000-yard year."],
  ["sanders-court", "Jauan Jennings", "WR", "SF", "San Francisco 49ers", "2021–present", 83, "Physical chain mover in January."],
  ["samuel-curtis", "Curtis Samuel", "WR", "WAS", "Washington Commanders", "2017–present", 82, "Motion weapon who scored from everywhere."],
  ["anderson-robby", "Robby Anderson", "WR", "CAR", "Carolina Panthers", "2016–2021", 82, "Go-ball specialist with a 1,000-yard year."],
  ["golladay", "Kenny Golladay", "WR", "DET", "Detroit Lions", "2017–2020", 83, "Jump-ball X with a 1,000-yard season."],
  ["shepard2", "Darius Slayton", "WR", "NYG", "New York Giants", "2019–present", 81, "Vertical Giant who would not leave."],
  ["pittman", "Michael Pittman Jr.", "WR", "IND", "Indianapolis Colts", "2020–present", 85, "Possession X with 100-catch gravity."],
  ["renfrow2", "Jakobi Meyers", "WR", "LV", "Las Vegas Raiders", "2019–present", 84, "Undrafted chain mover who became a WR1."],
  ["holland", "Nico Collins", "WR", "HOU", "Houston Texans", "2021–2023", 87, "Breakout body and YAC in Houston."],

  // Tight ends
  ["kelce", "Travis Kelce", "TE", "KC", "Kansas City Chiefs", "2016–present", 97, "The position, rewritten. Mahomes' security blanket."],
  ["gronk", "Rob Gronkowski", "TE", "NE", "New England Patriots", "2016–2018", 94, "Matchup nightmare and a blocking hammer."],
  ["gronk-tb", "Rob Gronkowski", "TE", "TB", "Tampa Bay Buccaneers", "2020–2021", 91, "The un-retirement. Two more rings."],
  ["kittle", "George Kittle", "TE", "SF", "San Francisco 49ers", "2017–present", 93, "YAC demon and the loudest blocker at the position."],
  ["andrews", "Mark Andrews", "TE", "BAL", "Baltimore Ravens", "2018–present", 89, "Lamar's favorite chain-mover."],
  ["olsen", "Greg Olsen", "TE", "CAR", "Carolina Panthers", "2016–2019", 86, "Cam's security blanket. 1,000-yard years."],
  ["mcbride", "Trey McBride", "TE", "ARI", "Arizona Cardinals", "2022–present", 88, "The new volume king in the desert."],
  ["bowers", "Brock Bowers", "TE", "LV", "Las Vegas Raiders", "2024–present", 89, "Rookie-year film that looks like a veteran."],
  ["ertz", "Zach Ertz", "TE", "PHI", "Philadelphia Eagles", "2016–2020", 87, "Philly Special catch and a 116-catch season."],
  ["laporta", "Sam LaPorta", "TE", "DET", "Detroit Lions", "2023–present", 87, "Rookie record-chaser in Detroit's explosion."],
  ["waller", "Darren Waller", "TE", "LV", "Las Vegas Raiders", "2019–2022", 88, "Comeback story and a 1,100-yard WR-in-disguise."],
  ["hock", "T.J. Hockenson", "TE", "MIN", "Minnesota Vikings", "2019–present", 85, "Move TE who produced in two cities."],
  ["goedert", "Dallas Goedert", "TE", "PHI", "Philadelphia Eagles", "2018–present", 85, "The other Eagle. YAC and reliability."],
  ["njoku", "David Njoku", "TE", "CLE", "Cleveland Browns", "2017–present", 85, "Athletic freak who finally put it together."],
  ["engram", "Evan Engram", "TE", "JAX", "Jacksonville Jaguars", "2017–present", 85, "WR-speed TE who bloomed in Jacksonville."],
  ["graham", "Jimmy Graham", "TE", "SEA", "Seattle Seahawks", "2016–2017", 86, "Red-zone mismatch in a new city."],
  ["witten", "Jason Witten", "TE", "DAL", "Dallas Cowboys", "2016–2017", 83, "Iron man over the middle, late career still useful."],
  ["gates", "Antonio Gates", "TE", "LAC", "Los Angeles Chargers", "2016–2018", 85, "Red-zone cheat code until the last snap."],
  ["kincaid", "Dalton Kincaid", "TE", "BUF", "Buffalo Bills", "2023–present", 83, "Move TE with WR hands."],
  ["kraft", "Tucker Kraft", "TE", "GB", "Green Bay Packers", "2023–present", 85, "YAC after the catch in Love's offense."],
  ["ferguson", "Jake Ferguson", "TE", "DAL", "Dallas Cowboys", "2022–present", 83, "Dak's new over-the-middle answer."],
  ["schultz", "Dalton Schultz", "TE", "HOU", "Houston Texans", "2018–present", 83, "Reliable mover in two offenses."],
  ["pitts", "Kyle Pitts", "TE", "ATL", "Atlanta Falcons", "2021–present", 84, "Athletic marvel still hunting chemistry."],
  ["likely", "Isaiah Likely", "TE", "BAL", "Baltimore Ravens", "2022–present", 82, "The other Raven with WR juice."],
  ["kmet", "Cole Kmet", "TE", "CHI", "Chicago Bears", "2020–present", 83, "In-line glue. Quietly productive."],
  ["freiermuth", "Pat Freiermuth", "TE", "PIT", "Pittsburgh Steelers", "2021–present", 83, "Big Ben's last security blanket, then the next one."],
  ["fant", "Noah Fant", "TE", "SEA", "Seattle Seahawks", "2019–present", 82, "Athletic move TE who produced in two cities."],
  ["gesicki", "Mike Gesicki", "TE", "MIA", "Miami Dolphins", "2018–2022", 84, "Basketball body. Move-TE in South Beach."],
  ["higbee", "Tyler Higbee", "TE", "LAR", "Los Angeles Rams", "2016–present", 83, "In-line Ram who popped in a Super Bowl year."],
  ["smith-jonnu", "Jonnu Smith", "TE", "MIA", "Miami Dolphins", "2017–present", 84, "YAC after the catch in multiple offenses."],
  ["knox", "Dawson Knox", "TE", "BUF", "Buffalo Bills", "2019–present", 82, "Red-zone athlete in an Allen offense."],
  ["kittle-wait2", "George Kittle", "TE", "SF", "San Francisco 49ers", "2018–2020", 93, "The 1,300-yard YAC season that rewrote the position."],
  ["kelce-prime", "Travis Kelce", "TE", "KC", "Kansas City Chiefs", "2018–2022", 97, "The unmatched peak. Super Bowl engine."],
  ["ertz-ari", "Zach Ertz", "TE", "ARI", "Arizona Cardinals", "2021–present", 81, "Veteran mover who kept catching first downs."],
  ["waller-nyg", "Darren Waller", "TE", "NYG", "New York Giants", "2023–present", 81, "The second act in blue."],
  ["andrews-prime", "Mark Andrews", "TE", "BAL", "Baltimore Ravens", "2019–2021", 89, "1,300-yard gravity next to Lamar."],
  ["hock-det", "T.J. Hockenson", "TE", "DET", "Detroit Lions", "2019–2022", 84, "First-round mover before the Minnesota chapter."],
  ["lafell-skip", "Hunter Henry", "TE", "NE", "New England Patriots", "2016–present", 84, "Reliable red-zone TE across two franchises."],
  ["engram-nyg", "Evan Engram", "TE", "NYG", "New York Giants", "2017–2021", 82, "WR-speed TE in the Odell years."],
  ["kmet-prime", "Cole Kmet", "TE", "CHI", "Chicago Bears", "2021–2023", 83, "The Bears' move-the-chains option."],

  // Extra last-decade depth so the board has a real rating spread
  ["ridley", "Calvin Ridley", "WR", "ATL", "Atlanta Falcons", "2018–2021", 86, "Route precision and a 1,000-yard leap in Atlanta."],
  ["jeudy", "Jerry Jeudy", "WR", "DEN", "Denver Broncos", "2020–present", 84, "Release artist who finally found a quarterback."],
  ["hollywood", "Marquise Brown", "WR", "BAL", "Baltimore Ravens", "2019–2022", 83, "Deep-ball cheetah next to Lamar."],
  ["shakir", "Khalil Shakir", "WR", "BUF", "Buffalo Bills", "2022–present", 84, "YAC slot who became Allen's chain-mover."],
  ["mooney", "Darnell Mooney", "WR", "CHI", "Chicago Bears", "2020–present", 83, "Vertical WR2 who posted a 1,000-yard year."],
  ["wan'dale", "Wan'Dale Robinson", "WR", "NYG", "New York Giants", "2022–present", 81, "Slot gadget with PPR weeks."],
  ["lazard", "Allen Lazard", "WR", "GB", "Green Bay Packers", "2018–2022", 81, "Red-zone X in a Rodgers huddle."],
  ["gallup", "Michael Gallup", "WR", "DAL", "Dallas Cowboys", "2018–2023", 82, "Boundary X next to Cooper and Lamb."],
  ["warren", "Jaylen Warren", "RB", "PIT", "Pittsburgh Steelers", "2022–present", 83, "Contact balance and receiving chops in Pittsburgh."],
  ["jwhite", "James White", "RB", "NE", "New England Patriots", "2016–2021", 84, "Passing-down assassin. Super Bowl walk-off."],
  ["rwhite", "Rachaad White", "RB", "TB", "Tampa Bay Buccaneers", "2022–present", 82, "Pass-catching lead in a new Bucs offense."],
  ["dowdle", "Rico Dowdle", "RB", "DAL", "Dallas Cowboys", "2020–present", 81, "Workhorse who took the keys and ran."],
  ["fields", "Justin Fields", "QB", "CHI", "Chicago Bears", "2021–2024", 82, "Designed-run dynamite with a 1,000-yard rushing year."],
  ["darnold", "Sam Darnold", "QB", "MIN", "Minnesota Vikings", "2018–present", 82, "The Minnesota resurrection. Playoff starter."],
  ["otton", "Cade Otton", "TE", "TB", "Tampa Bay Buccaneers", "2022–present", 82, "In-line Ram-killer in a Bucs offense."],
  ["conklin", "Tyler Conklin", "TE", "NYJ", "New York Jets", "2018–present", 81, "Move TE who produced in two cities."],
  ["jonnu-ne", "Jonnu Smith", "TE", "NE", "New England Patriots", "2021–2023", 80, "YAC piece in a committee before the Miami bloom."],
  ["boyd-prime", "Tyler Boyd", "WR", "CIN", "Cincinnati Bengals", "2018–2021", 80, "Slot glue on a Super Bowl roster."],

  // More last-decade depth so the dark pool stays well over 200 unique names
  ["garoppolo", "Jimmy Garoppolo", "QB", "SF", "San Francisco 49ers", "2017–2022", 84, "The 49ers' bridge to a Super Bowl."],
  ["foles", "Nick Foles", "QB", "PHI", "Philadelphia Eagles", "2017–2018", 85, "Philly Special. Super Bowl MVP."],
  ["alexsmith", "Alex Smith", "QB", "KC", "Kansas City Chiefs", "2016–2017", 84, "The calm before Mahomes. Then the comeback."],
  ["flacco", "Joe Flacco", "QB", "BAL", "Baltimore Ravens", "2016–2018", 82, "Elite Dragon twilight, still a January problem."],
  ["flacco-cle", "Joe Flacco", "QB", "CLE", "Cleveland Browns", "2023", 81, "Midseason rescue. Playoff starter at thirty-eight."],
  ["winston", "Jameis Winston", "QB", "NO", "New Orleans Saints", "2021–2022", 81, "Gunslinger who kept the Saints humming."],
  ["mariota", "Marcus Mariota", "QB", "TEN", "Tennessee Titans", "2016–2019", 82, "Zone-read lightning in a Titans huddle."],
  ["dalton", "Andy Dalton", "QB", "CIN", "Cincinnati Bengals", "2016–2019", 82, "Red Rifle. Yearly 3,500 without the January luck."],
  ["keenum", "Case Keenum", "QB", "MIN", "Minnesota Vikings", "2017", 83, "Minneapolis Miracle starter. The tape still holds."],
  ["teddy", "Teddy Bridgewater", "QB", "NO", "New Orleans Saints", "2018–2021", 81, "The comeback. Calm in a Saints huddle."],
  ["minshew", "Gardner Minshew", "QB", "JAX", "Jacksonville Jaguars", "2019–2020", 81, "Mustache, no-look, and a locker room."],
  ["brissett", "Jacoby Brissett", "QB", "IND", "Indianapolis Colts", "2017–2022", 80, "Bridge starter who never mailed it in."],
  ["fitz", "Ryan Fitzpatrick", "QB", "TB", "Tampa Bay Buccaneers", "2017–2020", 81, "Fitzmagic. Six different helmets, same chaos."],
  ["tyrod", "Tyrod Taylor", "QB", "BUF", "Buffalo Bills", "2016–2017", 81, "The dual-threat who kept Buffalo afloat."],
  ["djones", "Daniel Jones", "QB", "NYG", "New York Giants", "2019–2024", 82, "Danny Dimes. A playoff run out of nowhere."],
  ["macjones", "Mac Jones", "QB", "NE", "New England Patriots", "2021–2023", 80, "Rookie-year composure in a Patriot rebuild."],
  ["arich", "Anthony Richardson", "QB", "IND", "Indianapolis Colts", "2023–present", 80, "Physical prototype still hunting a full season."],
  ["camward", "Cam Ward", "QB", "TEN", "Tennessee Titans", "2025–present", 82, "First-overall live arm in a new Titans."],
  ["jdart", "Jaxson Dart", "QB", "NYG", "New York Giants", "2025–present", 80, "Big-armed Giant with a scramble gear."],
  ["carr-no", "Derek Carr", "QB", "NO", "New Orleans Saints", "2023–present", 83, "Veteran starter in a Saints huddle."],
  ["wilson-den", "Russell Wilson", "QB", "DEN", "Denver Broncos", "2022–2023", 82, "The Denver chapter. Still a problem on third down."],
  ["rodgers-nyj", "Aaron Rodgers", "QB", "NYJ", "New York Jets", "2023–present", 86, "The late New York experiment."],
  ["brady-ne", "Tom Brady", "QB", "NE", "New England Patriots", "2016–2019", 97, "The last Patriot dynasty. Still the standard."],
  ["stafford-det", "Matthew Stafford", "QB", "DET", "Detroit Lions", "2016–2020", 87, "Detroit warrior years before the ring."],
  ["mostert", "Raheem Mostert", "RB", "SF", "San Francisco 49ers", "2016–2022", 84, "Outside-zone home runs. Super Bowl thunder."],
  ["michel", "Sony Michel", "RB", "NE", "New England Patriots", "2018–2020", 83, "Super Bowl closer in a Patriot backfield."],
  ["penny", "Rashaad Penny", "RB", "SEA", "Seattle Seahawks", "2018–2022", 83, "When healthy, a 5.8-yard nightmare."],
  ["jwilliams-det", "Jamaal Williams", "RB", "DET", "Detroit Lions", "2021–2022", 84, "1,000-yard smile and a touchdown binge."],
  ["ceh", "Clyde Edwards-Helaire", "RB", "KC", "Kansas City Chiefs", "2020–present", 82, "First-round Chief. Super Bowl snaps included."],
  ["gibson", "Antonio Gibson", "RB", "WAS", "Washington Commanders", "2020–2023", 83, "Receiver-turned-back with 1,000-yard juice."],
  ["jrobinson", "James Robinson", "RB", "JAX", "Jacksonville Jaguars", "2020–2022", 84, "Undrafted 1,000-yard hammer."],
  ["dharris", "Damien Harris", "RB", "NE", "New England Patriots", "2019–2022", 82, "Between-tackle closer in Foxborough."],
  ["hines", "Nyheim Hines", "RB", "IND", "Indianapolis Colts", "2018–2022", 81, "Passing-down dart and a punt-return threat."],
  ["lmurray", "Latavius Murray", "RB", "MIN", "Minnesota Vikings", "2017–2021", 82, "Veteran closer who scored in bunches."],
  ["gore", "Frank Gore", "RB", "IND", "Indianapolis Colts", "2016–2019", 83, "The mileage. Still between the tackles at thirty-four."],
  ["adpeterson", "Adrian Peterson", "RB", "MIN", "Minnesota Vikings", "2016–2017", 84, "All Day. A 1,000-yard encore after the tear."],
  ["blount", "LeGarrette Blount", "RB", "NE", "New England Patriots", "2016", 82, "Goal-line tank on a Super Bowl roster."],
  ["gbernard", "Giovani Bernard", "RB", "CIN", "Cincinnati Bengals", "2016–2021", 81, "Change-of-pace glue for half a decade."],
  ["chyde", "Carlos Hyde", "RB", "SF", "San Francisco 49ers", "2016–2017", 81, "Between-tackle lead with a 1,000-yard sniff."],
  ["allgeier", "Tyler Allgeier", "RB", "ATL", "Atlanta Falcons", "2022–present", 82, "Contact balance behind Bijan."],
  ["roschon", "Roschon Johnson", "RB", "CHI", "Chicago Bears", "2023–present", 80, "Short-yardage hammer in Chicago."],
  ["bigsby", "Tank Bigsby", "RB", "JAX", "Jacksonville Jaguars", "2023–present", 81, "Explosive closer who took the keys in stretches."],
  ["ballen", "Braelon Allen", "RB", "NYJ", "New York Jets", "2024–present", 80, "Big-bodied change of pace in green."],
  ["tracy", "Tyrone Tracy Jr.", "RB", "NYG", "New York Giants", "2024–present", 82, "Converted WR who became a Giant workhorse."],
  ["benson", "Trey Benson", "RB", "ARI", "Arizona Cardinals", "2024–present", 80, "One-cut speed in a Cardinals committee."],
  ["hampton", "Omarion Hampton", "RB", "LAC", "Los Angeles Chargers", "2025–present", 83, "Day-one workhorse in a Herbert backfield."],
  ["judkins", "Quinshon Judkins", "RB", "CLE", "Cleveland Browns", "2025–present", 82, "Between-tackle hammer in brown."],
  ["thenderson", "TreVeyon Henderson", "RB", "NE", "New England Patriots", "2025–present", 82, "Home-run speed in a Patriot rebuild."],
  ["kaleb", "Kaleb Johnson", "RB", "PIT", "Pittsburgh Steelers", "2025–present", 80, "Outside-zone burst in black and gold."],
  ["baldwin", "Doug Baldwin", "WR", "SEA", "Seattle Seahawks", "2016–2018", 86, "Slot tough. Super Bowl hands in the Legion twilight."],
  ["gtate", "Golden Tate", "WR", "DET", "Detroit Lions", "2016–2018", 85, "YAC chaos. Punt-returner who became a WR1."],
  ["mjones", "Marvin Jones", "WR", "DET", "Detroit Lions", "2016–2020", 84, "Jump-ball X with a 1,000-yard year."],
  ["watkins", "Sammy Watkins", "WR", "KC", "Kansas City Chiefs", "2018–2020", 83, "The other Chief. Super Bowl speed."],
  ["djack", "DeSean Jackson", "WR", "WAS", "Washington", "2016–2019", 84, "Go-ball king who never lost the 4.3."],
  ["shepard", "Sterling Shepard", "WR", "NYG", "New York Giants", "2016–2023", 82, "Slot Giant who kept coming back."],
  ["cdavis", "Corey Davis", "WR", "TEN", "Tennessee Titans", "2017–2020", 83, "Big-bodied X on a playoff Titans roster."],
  ["chark", "D.J. Chark", "WR", "JAX", "Jacksonville Jaguars", "2018–2021", 83, "Deep threat with a 1,000-yard leap."],
  ["agholor", "Nelson Agholor", "WR", "PHI", "Philadelphia Eagles", "2016–2019", 82, "The Super Bowl slot who finally arrived."],
  ["sanu", "Mohamed Sanu", "WR", "ATL", "Atlanta Falcons", "2016–2019", 81, "Possession glue next to Julio."],
  ["beasley", "Cole Beasley", "WR", "BUF", "Buffalo Bills", "2019–2021", 82, "Slot technician in an Allen huddle."],
  ["crowder", "Jamison Crowder", "WR", "NYJ", "New York Jets", "2019–2021", 81, "PPR slot with 100-target gravity."],
  ["hardman", "Mecole Hardman", "WR", "KC", "Kansas City Chiefs", "2019–2022", 82, "Jet-sweep and go-ball in a dynasty."],
  ["tpatrick", "Tim Patrick", "WR", "DEN", "Denver Broncos", "2018–present", 82, "Boundary X who kept beating the injury sheet."],
  ["vjeff", "Van Jefferson", "WR", "LAR", "Los Angeles Rams", "2020–2022", 80, "Vertical Ram on a Super Bowl roster."],
  ["pearsall", "Ricky Pearsall", "WR", "SF", "San Francisco 49ers", "2024–present", 81, "Route polish who scored in January as a rookie."],
  ["legette", "Xavier Legette", "WR", "CAR", "Carolina Panthers", "2024–present", 80, "Size and a contested-catch leap."],
  ["adonai", "Adonai Mitchell", "WR", "IND", "Indianapolis Colts", "2024–present", 80, "Vertical juice in a Colts rebuild."],
  ["mcmillan-jalen", "Jalen McMillan", "WR", "TB", "Tampa Bay Buccaneers", "2024–present", 81, "The other Buc who took over when Evans sat."],
  ["tet", "Tetairoa McMillan", "WR", "CAR", "Carolina Panthers", "2025–present", 84, "Day-one X with a catch radius that swallows DBs."],
  ["egbuka", "Emeka Egbuka", "WR", "TB", "Tampa Bay Buccaneers", "2025–present", 83, "Polished rookie next to Evans."],
  ["burden", "Luther Burden III", "WR", "CHI", "Chicago Bears", "2025–present", 82, "YAC chaos in a new Bears offense."],
  ["thunter", "Travis Hunter", "WR", "JAX", "Jacksonville Jaguars", "2025–present", 84, "Two-way freak who lined up as a WR1."],
  ["mgolden", "Matthew Golden", "WR", "GB", "Green Bay Packers", "2025–present", 81, "Speed on the boundary in Love's offense."],
  ["jhiggin", "Jayden Higgins", "WR", "HOU", "Houston Texans", "2025–present", 81, "Size for Stroud on the outside."],
  ["dwalker", "Delanie Walker", "TE", "TEN", "Tennessee Titans", "2016–2019", 86, "1,000-yard mismatch before the position got loud."],
  ["jreed", "Jordan Reed", "TE", "WAS", "Washington", "2016–2019", 84, "Route-running TE who could not stay on the field."],
  ["ebron", "Eric Ebron", "TE", "IND", "Indianapolis Colts", "2018–2019", 84, "Red-zone binge in a Luck encore."],
  ["ahooper", "Austin Hooper", "TE", "ATL", "Atlanta Falcons", "2016–2019", 83, "Safety-valve TE with a 75-catch year."],
  ["jdoyle", "Jack Doyle", "TE", "IND", "Indianapolis Colts", "2016–2020", 82, "In-line glue and a red-zone answer."],
  ["brate", "Cameron Brate", "TE", "TB", "Tampa Bay Buccaneers", "2016–2022", 81, "Red-zone specialist on a Super Bowl roster."],
  ["jcook-te", "Jared Cook", "TE", "NO", "New Orleans Saints", "2019–2020", 83, "Move TE who popped in a Saints huddle."],
  ["everett", "Gerald Everett", "TE", "LAR", "Los Angeles Rams", "2017–2021", 82, "Athletic mismatch in two offenses."],
  ["dissly", "Will Dissly", "TE", "SEA", "Seattle Seahawks", "2018–2023", 81, "In-line Ram-killer when healthy."],
  ["jjohnson-te", "Juwan Johnson", "TE", "NO", "New Orleans Saints", "2020–present", 82, "Converted WR. Red-zone gravity in black and gold."],
  ["okonkwo", "Chigoziem Okonkwo", "TE", "TEN", "Tennessee Titans", "2022–present", 81, "YAC after the catch in Tennessee."],
  ["musgrave", "Luke Musgrave", "TE", "GB", "Green Bay Packers", "2023–present", 80, "Move TE in a Love offense."],
  ["mmayer", "Michael Mayer", "TE", "LV", "Las Vegas Raiders", "2023–present", 80, "In-line body still hunting a role."],
  ["loveland", "Colston Loveland", "TE", "CHI", "Chicago Bears", "2025–present", 83, "First-round mover in a Bears explosion."],
  ["twarren", "Tyler Warren", "TE", "IND", "Indianapolis Colts", "2025–present", 84, "Do-it-all rookie who lined up everywhere."],
  ["mtaylor-te", "Mason Taylor", "TE", "NYJ", "New York Jets", "2025–present", 80, "The other Taylor. Move TE in green."],
  ["jsanders-te", "Ja'Tavion Sanders", "TE", "CAR", "Carolina Panthers", "2024–present", 81, "YAC after the catch in Carolina."],
  ["ngray", "Noah Gray", "TE", "KC", "Kansas City Chiefs", "2021–present", 80, "The other Chief. Blocking and red-zone snaps."],
];

/** Reroll-only. Never on the opening board. One in ten spins lands here. */
const BUST_ROWS: Row[] = [
  ["peterman", "Nathan Peterman", "QB", "BUF", "Buffalo Bills", "2017–2022", 70, "Five picks before halftime. A cautionary tale."],
  ["rosen", "Josh Rosen", "QB", "ARI", "Arizona Cardinals", "2018–2019", 70, "Tenth overall. The desert did not bloom."],
  ["lynch-pax", "Paxton Lynch", "QB", "DEN", "Denver Broncos", "2016–2017", 70, "First-round arm that never found the timing."],
  ["haskins", "Dwayne Haskins", "QB", "WAS", "Washington", "2019–2020", 70, "First-rounder who never seized the huddle."],
  ["zwilson", "Zach Wilson", "QB", "NYJ", "New York Jets", "2021–2023", 70, "Second overall. The resets outnumbered the wins."],
  ["tboyle", "Tim Boyle", "QB", "GB", "Green Bay Packers", "2019–present", 70, "Clipboard emergency that stayed an emergency."],
  ["ehlinger", "Sam Ehlinger", "QB", "IND", "Indianapolis Colts", "2021–present", 70, "Tough kid. The tape stayed tough to watch."],
  ["fromm", "Jake Fromm", "QB", "BUF", "Buffalo Bills", "2021–2022", 70, "Game manager who rarely found a game."],
  ["ksvaughn", "Ke'Shawn Vaughn", "RB", "TB", "Tampa Bay Buccaneers", "2020–2023", 70, "Day-two pick buried on a Super Bowl depth chart."],
  ["snell", "Benny Snell Jr.", "RB", "PIT", "Pittsburgh Steelers", "2019–2022", 70, "Between-tackle thumper who stayed a committee ghost."],
  ["ollison", "Qadree Ollison", "RB", "ATL", "Atlanta Falcons", "2019–2022", 70, "Goal-line look that never became a role."],
  ["dhenderson", "Darrell Henderson", "RB", "LAR", "Los Angeles Rams", "2019–2022", 70, "Explosive weeks, then the next man up."],
  ["sconner", "Snoop Conner", "RB", "JAX", "Jacksonville Jaguars", "2022–2023", 70, "Depth-chart name. Depth-chart production."],
  ["tchandler", "Ty Chandler", "RB", "MIN", "Minnesota Vikings", "2022–present", 70, "Change-of-pace who never seized the pace."],
  ["jjefferson-rb", "Jermar Jefferson", "RB", "DET", "Detroit Lions", "2021–present", 70, "Practice-squad thunder that stayed in thunder."],
  ["zwhite", "Zamir White", "RB", "LV", "Las Vegas Raiders", "2022–present", 70, "Workhorse look that faded when the lights hit."],
  ["nharry", "N'Keal Harry", "WR", "NE", "New England Patriots", "2019–2022", 70, "First-round target who could not get open."],
  ["reagor", "Jalen Reagor", "WR", "PHI", "Philadelphia Eagles", "2020–2022", 70, "The other first-rounder. Hands were the plot."],
  ["dmims", "Denzel Mims", "WR", "NYJ", "New York Jets", "2020–2022", 70, "Size and speed that never became a route tree."],
  ["hamler", "KJ Hamler", "WR", "DEN", "Denver Broncos", "2020–2023", 70, "Deep threat whose availability was the story."],
  ["jross", "John Ross", "WR", "CIN", "Cincinnati Bengals", "2017–2020", 70, "Combine king. The pads never caught the 4.22."],
  ["treadwell", "Laquon Treadwell", "WR", "MIN", "Minnesota Vikings", "2016–2019", 70, "Top-ten WR who became a footnote."],
  ["eqstbrown", "Equanimeous St. Brown", "WR", "GB", "Green Bay Packers", "2018–2021", 70, "The other St. Brown. Mostly a special-teamer."],
  ["guyton", "Jalen Guyton", "WR", "LAC", "Los Angeles Chargers", "2020–2023", 70, "Go-ball look that stayed a look."],
  ["irvsmith", "Irv Smith Jr.", "TE", "MIN", "Minnesota Vikings", "2019–2022", 70, "Move TE whose availability never stacked."],
  ["trautman", "Adam Trautman", "TE", "NO", "New Orleans Saints", "2020–present", 70, "Day-two body that stayed a blocker."],
  ["cturner", "Cole Turner", "TE", "WAS", "Washington Commanders", "2022–present", 70, "Red-zone size still hunting a role."],
  ["jwoods", "Jelani Woods", "TE", "IND", "Indianapolis Colts", "2022–present", 70, "Athletic mismatch that stayed on the shelf."],
  ["ruckert", "Jeremy Ruckert", "TE", "NYJ", "New York Jets", "2022–present", 70, "In-line piece behind the in-line piece."],
  ["schoon", "Luke Schoonmaker", "TE", "DAL", "Dallas Cowboys", "2023–present", 70, "Day-two Cowboy still waiting on targets."],
  ["calcaterra", "Grant Calcaterra", "TE", "PHI", "Philadelphia Eagles", "2022–present", 70, "Blocking TE on a star-heavy roster."],
  ["moreau", "Foster Moreau", "TE", "LV", "Las Vegas Raiders", "2019–2022", 70, "In-line glue who never became the guy."],
  ["tlance", "Trey Lance", "QB", "SF", "San Francisco 49ers", "2021–2023", 70, "Three first-round picks. The starts never stacked."],
  ["pickett", "Kenny Pickett", "QB", "PIT", "Pittsburgh Steelers", "2022–2023", 70, "First-rounder who stayed a question."],
  ["ridder", "Desmond Ridder", "QB", "ATL", "Atlanta Falcons", "2022–2023", 70, "The other first-round night. The tape stayed shy."],
  ["howell", "Sam Howell", "QB", "WAS", "Washington Commanders", "2022–2023", 70, "Iron-man year that did not become a job."],
  ["levis", "Will Levis", "QB", "TEN", "Tennessee Titans", "2023–present", 70, "The cannon. The resets."],
  ["mills", "Davis Mills", "QB", "HOU", "Houston Texans", "2021–present", 70, "Bridge starter who stayed a bridge."],
  ["zappe", "Bailey Zappe", "QB", "NE", "New England Patriots", "2022–2024", 70, "Emergency arm. Emergency production."],
  ["mwills", "Malik Willis", "QB", "TEN", "Tennessee Titans", "2022–present", 70, "Athlete first. The throws came second."],
  ["piercem", "Pierre Strong Jr.", "RB", "NE", "New England Patriots", "2022–present", 70, "Juice on the depth chart that stayed on the depth chart."],
  ["riversp", "Ronnie Rivers", "RB", "LAR", "Los Angeles Rams", "2022–present", 70, "Practice-squad thunder."],
  ["kherbert", "Khalil Herbert", "RB", "CHI", "Chicago Bears", "2021–2023", 70, "Change-of-pace who never seized the job."],
  ["ceh-late", "Michael Carter", "RB", "NYJ", "New York Jets", "2021–2023", 70, "Committee back who faded when the snaps dried."],
  ["dpierce", "Dameon Pierce", "RB", "HOU", "Houston Texans", "2022–present", 70, "Rookie thunder, then the committee."],
  ["jmeute", "Jonathan Mingo", "WR", "CAR", "Carolina Panthers", "2023–present", 70, "Day-two size that never became a route tree."],
  ["jdotson", "Jahan Dotson", "WR", "WAS", "Washington Commanders", "2022–present", 70, "First-round slot still hunting a role."],
  ["skyy", "Skyy Moore", "WR", "KC", "Kansas City Chiefs", "2022–present", 70, "Day-two Chief who stayed a gadget."],
  ["wan'dale-bust", "Justyn Ross", "WR", "KC", "Kansas City Chiefs", "2022–present", 70, "The other Chief. The targets never came."],
  ["bateman-bust", "Rashod Bateman", "WR", "BAL", "Baltimore Ravens", "2021–2022", 70, "First-round X whose availability was the plot."],
];

function lastNameKey(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

function applyCareer(player: Player): Player {
  const fix = CAREER[player.name];
  if (!fix) return { ...player, teams: player.teams?.length ? player.teams : [player.team] };
  const team = fix.team ?? player.team;
  const info = teamById(team);
  const teams = (fix.teams?.length ? fix.teams : [team]).slice(0, 2);
  if (!info) return { ...player, years: fix.years, note: fix.note ?? player.note, teams };
  return {
    ...player,
    years: fix.years,
    team,
    teamName: `${info.city} ${info.nick}`,
    note: fix.note ?? player.note,
    teams,
  };
}

const mapped: Player[] = ROWS.map(([id, name, position, team, teamName, years, rating, note]) => ({
  id: `${id}-${team}-${lastNameKey(name)}`,
  name,
  position,
  team,
  teamName,
  years,
  rating,
  note,
  teams: [team],
}));

const best = new Map<string, Player>();
for (const player of mapped) {
  if (player.rating < 80) continue;
  const key = `${player.position}:${player.name}`;
  const prev = best.get(key);
  if (!prev || player.rating > prev.rating) best.set(key, player);
}

export const PLAYERS: Player[] = [...best.values()].map(applyCareer).map(applyBestSeason);

function mapRows(rows: Row[]): Player[] {
  return rows.map(([id, name, position, team, teamName, years, rating, note]) => ({
    id: `${id}-${team}-${lastNameKey(name)}`,
    name,
    position,
    team,
    teamName,
    years,
    rating,
    note,
    teams: [team],
  }));
}

export const BUSTS: Player[] = mapRows(BUST_ROWS);

