-- Public HTTP book snapshot. No player_nights, no darkness_results, no emails.
-- Coins/owned/stars as dumped. seed_lock keeps settleProfile from rewriting them.
create table if not exists darkness_payouts (
  id serial primary key,
  user_id text not null,
  amount integer not null,
  stars integer not null default 0,
  kind text not null,
  source_key text not null unique,
  created_at timestamptz not null default now()
);

insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, career_book, updated_at) values ('L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', 'knight', 'Pat', 1, 30, '["poor","rockstar","superhero","ninja","samurai","pilot","lumberjack","knight","werewolf","foam","wizard","peeping","reaper","agent","santa"]'::text, 0, 1, 4, 1, '{"total":{"games":59,"wins":30,"losses":29,"ties":0,"highest":173,"lowest":58},"auction":{"games":25,"wins":13,"losses":12,"ties":0,"highest":557,"lowest":519},"elimination":{"games":34,"wins":17,"losses":17,"ties":0,"highest":173,"lowest":58}}'::jsonb, now()) on conflict (user_id) do update set avatar_id = excluded.avatar_id, display_name = excluded.display_name, coins = excluded.coins, coin_wins = excluded.coin_wins, owned = excluded.owned, daily_stars = excluded.daily_stars, closet_reset = excluded.closet_reset, seed_lock = excluded.seed_lock, career_book = excluded.career_book, updated_at = now();
insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, career_book, updated_at) values ('WJ5wZKjoZwydfPBf5FrkiOdwYarlw7b7', 'superhero', 'Ty', 4, 17, '["poor","ninja","lumberjack","chef","zombie","pharaoh","pilot","superhero","hacker","cyborg","birthday","viking","pirate","holy-red"]'::text, 0, 0, 4, 1, '{"total":{"games":32,"wins":17,"losses":15,"ties":0,"highest":153,"lowest":70},"auction":{"games":21,"wins":9,"losses":12,"ties":0,"highest":550,"lowest":523},"elimination":{"games":11,"wins":8,"losses":3,"ties":0,"highest":153,"lowest":70}}'::jsonb, now()) on conflict (user_id) do update set avatar_id = excluded.avatar_id, display_name = excluded.display_name, coins = excluded.coins, coin_wins = excluded.coin_wins, owned = excluded.owned, daily_stars = excluded.daily_stars, closet_reset = excluded.closet_reset, seed_lock = excluded.seed_lock, career_book = excluded.career_book, updated_at = now();
insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, career_book, updated_at) values ('Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', 'wallstreet', 'WWW', 2, 15, '["poor","rockstar","hotdog","chef","vampire","agent","foam","holy-blue","wallstreet"]'::text, 0, 1, 4, 1, '{"total":{"games":20,"wins":15,"losses":5,"ties":0,"highest":168,"lowest":94},"auction":{"games":2,"wins":2,"losses":0,"ties":0,"highest":541,"lowest":533},"elimination":{"games":18,"wins":13,"losses":5,"ties":0,"highest":168,"lowest":94}}'::jsonb, now()) on conflict (user_id) do update set avatar_id = excluded.avatar_id, display_name = excluded.display_name, coins = excluded.coins, coin_wins = excluded.coin_wins, owned = excluded.owned, daily_stars = excluded.daily_stars, closet_reset = excluded.closet_reset, seed_lock = excluded.seed_lock, career_book = excluded.career_book, updated_at = now();
insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, career_book, updated_at) values ('t4GKnuNe18istHzOAvqGUgwVVnlV5WZ3', 'supervillain', 'Heisenberg', 3, 11, '["poor","supervillain","hotdog","chef","hacker","peeping"]'::text, 0, 0, 4, 1, '{"total":{"games":16,"wins":11,"losses":5,"ties":0,"highest":151,"lowest":92},"auction":{"games":1,"wins":1,"losses":0,"ties":0,"highest":543,"lowest":543},"elimination":{"games":15,"wins":10,"losses":5,"ties":0,"highest":151,"lowest":92}}'::jsonb, now()) on conflict (user_id) do update set avatar_id = excluded.avatar_id, display_name = excluded.display_name, coins = excluded.coins, coin_wins = excluded.coin_wins, owned = excluded.owned, daily_stars = excluded.daily_stars, closet_reset = excluded.closet_reset, seed_lock = excluded.seed_lock, career_book = excluded.career_book, updated_at = now();
insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, career_book, updated_at) values ('hxIAsCe4u3Ojx0jq5Zvvm2gsIcVeJw1A', 'club200', 'JSwanny', 8, 7, '["poor","club200","pilot"]'::text, 0, 0, 4, 1, '{"total":{"games":17,"wins":7,"losses":10,"ties":0,"highest":203,"lowest":91},"auction":{"games":0,"wins":0,"losses":0,"ties":0,"highest":null,"lowest":null},"elimination":{"games":17,"wins":7,"losses":10,"ties":0,"highest":203,"lowest":91}}'::jsonb, now()) on conflict (user_id) do update set avatar_id = excluded.avatar_id, display_name = excluded.display_name, coins = excluded.coins, coin_wins = excluded.coin_wins, owned = excluded.owned, daily_stars = excluded.daily_stars, closet_reset = excluded.closet_reset, seed_lock = excluded.seed_lock, career_book = excluded.career_book, updated_at = now();
insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, career_book, updated_at) values ('38GXVpMo8GE8bERLYLHaoQF4CPBjvUS0', 'santa', 'MSwan', 7, 7, '["poor","santa","foam"]'::text, 0, 1, 4, 1, '{"total":{"games":12,"wins":7,"losses":5,"ties":0,"highest":169,"lowest":122},"auction":{"games":0,"wins":0,"losses":0,"ties":0,"highest":null,"lowest":null},"elimination":{"games":12,"wins":7,"losses":5,"ties":0,"highest":169,"lowest":122}}'::jsonb, now()) on conflict (user_id) do update set avatar_id = excluded.avatar_id, display_name = excluded.display_name, coins = excluded.coins, coin_wins = excluded.coin_wins, owned = excluded.owned, daily_stars = excluded.daily_stars, closet_reset = excluded.closet_reset, seed_lock = excluded.seed_lock, career_book = excluded.career_book, updated_at = now();
insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, career_book, updated_at) values ('B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', 'wizard', 'Marquis Scott', 3, 4, '["poor","birthday","foam","peeping","wizard","detective","ninja","dj"]'::text, 0, 3, 4, 1, '{"total":{"games":18,"wins":4,"losses":14,"ties":0,"highest":172,"lowest":88},"auction":{"games":1,"wins":0,"losses":1,"ties":0,"highest":524,"lowest":524},"elimination":{"games":17,"wins":4,"losses":13,"ties":0,"highest":172,"lowest":88}}'::jsonb, now()) on conflict (user_id) do update set avatar_id = excluded.avatar_id, display_name = excluded.display_name, coins = excluded.coins, coin_wins = excluded.coin_wins, owned = excluded.owned, daily_stars = excluded.daily_stars, closet_reset = excluded.closet_reset, seed_lock = excluded.seed_lock, career_book = excluded.career_book, updated_at = now();
insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, career_book, updated_at) values ('e7APj7EJ03oPUXuukNxNpWqDzsCjUrIM', 'poor', 'Commish', 2, 2, '["poor"]'::text, 0, 0, 4, 1, '{"total":{"games":3,"wins":2,"losses":1,"ties":0,"highest":99,"lowest":99},"auction":{"games":0,"wins":0,"losses":0,"ties":0,"highest":null,"lowest":null},"elimination":{"games":3,"wins":2,"losses":1,"ties":0,"highest":99,"lowest":99}}'::jsonb, now()) on conflict (user_id) do update set avatar_id = excluded.avatar_id, display_name = excluded.display_name, coins = excluded.coins, coin_wins = excluded.coin_wins, owned = excluded.owned, daily_stars = excluded.daily_stars, closet_reset = excluded.closet_reset, seed_lock = excluded.seed_lock, career_book = excluded.career_book, updated_at = now();
insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, career_book, updated_at) values ('v783SxZeXud3WKr9H7q7pcgFypgIuGsY', 'cowboy', 'Stevo', 1, 1, '["poor","cowboy"]'::text, 0, 0, 4, 1, '{"total":{"games":2,"wins":1,"losses":1,"ties":0,"highest":125,"lowest":123},"auction":{"games":0,"wins":0,"losses":0,"ties":0,"highest":null,"lowest":null},"elimination":{"games":2,"wins":1,"losses":1,"ties":0,"highest":125,"lowest":123}}'::jsonb, now()) on conflict (user_id) do update set avatar_id = excluded.avatar_id, display_name = excluded.display_name, coins = excluded.coins, coin_wins = excluded.coin_wins, owned = excluded.owned, daily_stars = excluded.daily_stars, closet_reset = excluded.closet_reset, seed_lock = excluded.seed_lock, career_book = excluded.career_book, updated_at = now();
insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, career_book, updated_at) values ('d9UdHOqeb48BAXYizwiBkNOBGSB1jtXP', 'poor', 'Marquise Bessell', 1, 0, '["poor"]'::text, 0, 0, 4, 1, '{"total":{"games":1,"wins":0,"losses":1,"ties":0,"highest":107,"lowest":107},"auction":{"games":0,"wins":0,"losses":0,"ties":0,"highest":null,"lowest":null},"elimination":{"games":1,"wins":0,"losses":1,"ties":0,"highest":107,"lowest":107}}'::jsonb, now()) on conflict (user_id) do update set avatar_id = excluded.avatar_id, display_name = excluded.display_name, coins = excluded.coins, coin_wins = excluded.coin_wins, owned = excluded.owned, daily_stars = excluded.daily_stars, closet_reset = excluded.closet_reset, seed_lock = excluded.seed_lock, career_book = excluded.career_book, updated_at = now();
insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, updated_at) values ('Qxo7D6xMnqUdJ2pTikGalBsvfoLdd4MY', 'poor', 'Jay Mack', 0, 0, '["poor"]', 0, 0, 4, 1, now()) on conflict (user_id) do update set display_name = excluded.display_name, seed_lock = 1, updated_at = now();
insert into player_profiles (user_id, avatar_id, display_name, coins, coin_wins, owned, credit, daily_stars, closet_reset, seed_lock, updated_at) values ('5nWDuHgSRx1TLr0oeKtiStulZzievyRq', 'poor', 'Max Faile', 0, 0, '["poor"]', 0, 0, 4, 1, now()) on conflict (user_id) do update set display_name = excluded.display_name, seed_lock = 1, updated_at = now();

insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('hxIAsCe4u3Ojx0jq5Zvvm2gsIcVeJw1A', 1, 0, 'daily_score', 'daily_score:2026-09-08:hxIAsCe4u3Ojx0jq5Zvvm2gsIcVeJw1A', '2026-09-08T21:01:24.497Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('d9UdHOqeb48BAXYizwiBkNOBGSB1jtXP', 1, 0, 'daily_score', 'daily_score:2026-09-08:d9UdHOqeb48BAXYizwiBkNOBGSB1jtXP', '2026-09-08T15:44:56.137Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('Qxo7D6xMnqUdJ2pTikGalBsvfoLdd4MY', 1, 0, 'daily_score', 'daily_score:2026-09-08:Qxo7D6xMnqUdJ2pTikGalBsvfoLdd4MY', '2026-09-08T12:10:12.347Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', 1, 0, 'daily_score', 'daily_score:2026-09-08:Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', '2026-09-08T11:24:46.030Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('v783SxZeXud3WKr9H7q7pcgFypgIuGsY', 1, 0, 'daily_score', 'daily_score:2026-09-08:v783SxZeXud3WKr9H7q7pcgFypgIuGsY', '2026-09-08T11:22:22.127Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('t4GKnuNe18istHzOAvqGUgwVVnlV5WZ3', 1, 0, 'daily_score', 'daily_score:2026-09-08:t4GKnuNe18istHzOAvqGUgwVVnlV5WZ3', '2026-09-08T09:03:56.692Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('hxIAsCe4u3Ojx0jq5Zvvm2gsIcVeJw1A', 1, 0, 'daily_score', 'daily_score:2026-09-07:hxIAsCe4u3Ojx0jq5Zvvm2gsIcVeJw1A', '2026-09-07T16:15:32.169Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('v783SxZeXud3WKr9H7q7pcgFypgIuGsY', 1, 0, 'daily_score', 'daily_score:2026-09-07:v783SxZeXud3WKr9H7q7pcgFypgIuGsY', '2026-09-07T15:05:48.712Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', 1, 0, 'daily_score', 'daily_score:2026-09-07:Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', '2026-09-07T14:54:28.758Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', 1, 0, 'daily_score', 'daily_score:2026-09-07:B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', '2026-09-07T14:47:15.621Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', 1, 0, 'daily_score', 'daily_score:2026-09-07:L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', '2026-09-07T12:14:42.692Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('WJ5wZKjoZwydfPBf5FrkiOdwYarlw7b7', 1, 0, 'daily_score', 'daily_score:2026-09-07:WJ5wZKjoZwydfPBf5FrkiOdwYarlw7b7', '2026-09-07T10:23:40.076Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('38GXVpMo8GE8bERLYLHaoQF4CPBjvUS0', 1, 1, 'daily_win', 'daily_win:2026-09-07:38GXVpMo8GE8bERLYLHaoQF4CPBjvUS0', '2026-09-07T05:24:21.563Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('38GXVpMo8GE8bERLYLHaoQF4CPBjvUS0', 1, 0, 'daily_score', 'daily_score:2026-09-07:38GXVpMo8GE8bERLYLHaoQF4CPBjvUS0', '2026-09-07T05:24:21.563Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', 1, 0, 'daily_score', 'daily_score:2026-09-06:Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', '2026-09-06T18:33:25.831Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', 1, 1, 'daily_win', 'daily_win:2026-09-06:B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', '2026-09-06T18:26:58.149Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', 1, 0, 'daily_score', 'daily_score:2026-09-06:B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', '2026-09-06T18:26:58.149Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('t4GKnuNe18istHzOAvqGUgwVVnlV5WZ3', 1, 0, 'daily_score', 'daily_score:2026-09-06:t4GKnuNe18istHzOAvqGUgwVVnlV5WZ3', '2026-09-06T18:04:51.216Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('v783SxZeXud3WKr9H7q7pcgFypgIuGsY', 1, 0, 'daily_score', 'daily_score:2026-09-06:v783SxZeXud3WKr9H7q7pcgFypgIuGsY', '2026-09-06T17:00:00.947Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('hxIAsCe4u3Ojx0jq5Zvvm2gsIcVeJw1A', 1, 0, 'daily_score', 'daily_score:2026-09-06:hxIAsCe4u3Ojx0jq5Zvvm2gsIcVeJw1A', '2026-09-06T16:40:47.393Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('38GXVpMo8GE8bERLYLHaoQF4CPBjvUS0', 1, 0, 'daily_score', 'daily_score:2026-09-06:38GXVpMo8GE8bERLYLHaoQF4CPBjvUS0', '2026-09-06T16:39:41.746Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', 1, 0, 'daily_score', 'daily_score:2026-09-06:L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', '2026-09-06T12:06:31.937Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('5nWDuHgSRx1TLr0oeKtiStulZzievyRq', 1, 0, 'daily_score', 'daily_score:2026-09-05:5nWDuHgSRx1TLr0oeKtiStulZzievyRq', '2026-09-06T02:04:35.098Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', 1, 1, 'daily_win', 'daily_win:2026-09-05:B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', '2026-09-05T14:12:11.914Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', 1, 0, 'daily_score', 'daily_score:2026-09-05:B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', '2026-09-05T14:12:11.914Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', 1, 0, 'daily_score', 'daily_score:2026-09-05:Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', '2026-09-05T14:10:38.131Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', 1, 0, 'daily_score', 'daily_score:2026-09-05:L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', '2026-09-05T11:42:41.964Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('WJ5wZKjoZwydfPBf5FrkiOdwYarlw7b7', 1, 0, 'daily_score', 'daily_score:2026-09-05:WJ5wZKjoZwydfPBf5FrkiOdwYarlw7b7', '2026-09-05T10:12:50.914Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('5nWDuHgSRx1TLr0oeKtiStulZzievyRq', 1, 0, 'daily_score', 'daily_score:2026-09-04:5nWDuHgSRx1TLr0oeKtiStulZzievyRq', '2026-09-04T18:29:06.837Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('hxIAsCe4u3Ojx0jq5Zvvm2gsIcVeJw1A', 1, 0, 'daily_score', 'daily_score:2026-09-04:hxIAsCe4u3Ojx0jq5Zvvm2gsIcVeJw1A', '2026-09-04T17:52:20.578Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', 1, 1, 'daily_win', 'daily_win:2026-09-04:B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', '2026-09-04T17:06:19.272Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', 1, 0, 'daily_score', 'daily_score:2026-09-04:B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', '2026-09-04T17:06:19.272Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('WJ5wZKjoZwydfPBf5FrkiOdwYarlw7b7', 1, 0, 'daily_score', 'daily_score:2026-09-04:WJ5wZKjoZwydfPBf5FrkiOdwYarlw7b7', '2026-09-04T15:08:49.791Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('t4GKnuNe18istHzOAvqGUgwVVnlV5WZ3', 1, 0, 'daily_score', 'daily_score:2026-09-04:t4GKnuNe18istHzOAvqGUgwVVnlV5WZ3', '2026-09-04T12:53:51.810Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', 1, 0, 'daily_score', 'daily_score:2026-09-04:Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', '2026-09-04T12:47:21.859Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', 1, 0, 'daily_score', 'daily_score:2026-09-04:L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', '2026-09-04T12:44:13.264Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('5nWDuHgSRx1TLr0oeKtiStulZzievyRq', 1, 0, 'daily_score', 'daily_score:2026-09-03:5nWDuHgSRx1TLr0oeKtiStulZzievyRq', '2026-09-03T16:52:03.171Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('t4GKnuNe18istHzOAvqGUgwVVnlV5WZ3', 1, 0, 'daily_score', 'daily_score:2026-09-03:t4GKnuNe18istHzOAvqGUgwVVnlV5WZ3', '2026-09-03T15:09:17.709Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', 1, 1, 'daily_win', 'daily_win:2026-09-03:Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', '2026-09-03T15:06:25.174Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', 1, 0, 'daily_score', 'daily_score:2026-09-03:Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', '2026-09-03T15:06:25.174Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', 1, 0, 'daily_score', 'daily_score:2026-09-03:L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', '2026-09-03T12:07:02.469Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('WJ5wZKjoZwydfPBf5FrkiOdwYarlw7b7', 1, 0, 'daily_score', 'daily_score:2026-09-03:WJ5wZKjoZwydfPBf5FrkiOdwYarlw7b7', '2026-09-03T09:08:47.245Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', 1, 0, 'daily_score', 'daily_score:2026-09-02:Th7Ewogxh5Ul0nRrTQgs7tmP45rePO3Q', '2026-09-02T19:01:26.430Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', 1, 0, 'daily_score', 'daily_score:2026-09-02:B8FgPeYF2jVeLnfgd20PE8FYCpmpsC9n', '2026-09-02T18:40:59.571Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', 1, 1, 'daily_win', 'daily_win:2026-09-02:L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', '2026-09-02T17:26:06.084Z'::timestamptz) on conflict (source_key) do nothing;
insert into darkness_payouts (user_id, amount, stars, kind, source_key, created_at) values ('L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', 1, 0, 'daily_score', 'daily_score:2026-09-02:L2L2Tf1HXAeB5rhgLvhogF921BKsICsN', '2026-09-02T17:26:06.084Z'::timestamptz) on conflict (source_key) do nothing;
