/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiPayoutsRouteImport } from './routes/api/payouts'
import { Route as ApiRankingsRouteImport } from './routes/api/rankings'
import { Route as PlayerIdRouteImport } from './routes/player/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayoutsRoute = ApiPayoutsRouteImport.update({
  id: '/api/payouts',
  path: '/api/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRankingsRoute = ApiRankingsRouteImport.update({
  id: '/api/rankings',
  path: '/api/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdRoute = PlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rankings': typeof RankingsRoute
  '/recap': typeof RecapRoute
  '/settings': typeof SettingsRoute
  '/api/payouts': typeof ApiPayoutsRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/player/$id': typeof PlayerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rankings': typeof RankingsRoute
  '/recap': typeof RecapRoute
  '/settings': typeof SettingsRoute
  '/api/payouts': typeof ApiPayoutsRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/player/$id': typeof PlayerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rankings': typeof RankingsRoute
  '/recap': typeof RecapRoute
  '/settings': typeof SettingsRoute
  '/api/payouts': typeof ApiPayoutsRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/player/$id': typeof PlayerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/rankings'
    | '/recap'
    | '/settings'
    | '/api/payouts'
    | '/api/rankings'
    | '/player/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/rankings'
    | '/recap'
    | '/settings'
    | '/api/payouts'
    | '/api/rankings'
    | '/player/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/rankings'
    | '/recap'
    | '/settings'
    | '/api/payouts'
    | '/api/rankings'
    | '/player/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RankingsRoute: typeof RankingsRoute
  RecapRoute: typeof RecapRoute
  SettingsRoute: typeof SettingsRoute
  ApiPayoutsRoute: typeof ApiPayoutsRoute
  ApiRankingsRoute: typeof ApiRankingsRoute
  PlayerIdRoute: typeof PlayerIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payouts': {
      id: '/api/payouts'
      path: '/api/payouts'
      fullPath: '/api/payouts'
      preLoaderRoute: typeof ApiPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rankings': {
      id: '/api/rankings'
      path: '/api/rankings'
      fullPath: '/api/rankings'
      preLoaderRoute: typeof ApiRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id': {
      id: '/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof PlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RankingsRoute: RankingsRoute,
  RecapRoute: RecapRoute,
  SettingsRoute: SettingsRoute,
  ApiPayoutsRoute: ApiPayoutsRoute,
  ApiRankingsRoute: ApiRankingsRoute,
  PlayerIdRoute: PlayerIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
